org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
FIREBASE_APP_ID=1:671225940988:android:61799d65ca5fc091fb0079
FIREBASE_API_KEY=AIzaSyB_0bKAPQiYiod-SxyhadQdxWa1k71yRnk
FIREBASE_PROJECT_ID=shosetsu-toukou-site
FIREBASE_MESSAGING_SENDER_ID=671225940988
