version = 5.1.0
archive_dir = /etc/letsencrypt/archive/shosetsu-toukou-site.org
cert = /etc/letsencrypt/live/shosetsu-toukou-site.org/cert.pem
privkey = /etc/letsencrypt/live/shosetsu-toukou-site.org/privkey.pem
chain = /etc/letsencrypt/live/shosetsu-toukou-site.org/chain.pem
fullchain = /etc/letsencrypt/live/shosetsu-toukou-site.org/fullchain.pem
[renewalparams]
account = 4ad6a90874591baed2e79fa37e5f1f52
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
shosetsu-toukou-site.org = /var/www/certbot
www.shosetsu-toukou-site.org = /var/www/certbot
[acme_renewal_info]
ari_retry_after = 2025-12-22T10:00:05
