package com.novelsite.mobile
import android.os.Bundle
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import androidx.security.crypto.EncryptedSharedPreferences
import androidx.security.crypto.MasterKey
import okhttp3.*
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONObject
import java.io.IOException
import java.util.concurrent.TimeUnit
class AiChatActivity:AppCompatActivity(){
 private val client=OkHttpClient.Builder().readTimeout(180,TimeUnit.SECONDS).build();private lateinit var character:EditText;private lateinit var personality:EditText;private lateinit var subcharacters:EditText;private lateinit var model:Spinner;private lateinit var adult:CheckBox;private lateinit var style:Spinner;private lateinit var messages:LinearLayout;private lateinit var input:EditText;private lateinit var status:TextView
 private val prefs by lazy{getSharedPreferences("lexis_native_ai_chat",MODE_PRIVATE)};private val secure by lazy{val mk=MasterKey.Builder(this).setKeyScheme(MasterKey.KeyScheme.AES256_GCM).build();EncryptedSharedPreferences.create(this,"lexis_secure",mk,EncryptedSharedPreferences.PrefKeyEncryptionScheme.AES256_SIV,EncryptedSharedPreferences.PrefValueEncryptionScheme.AES256_GCM)}
 override fun onCreate(b:Bundle?){super.onCreate(b);setContentView(R.layout.activity_ai_chat);character=findViewById(R.id.chatCharacter);personality=findViewById(R.id.chatPersonality);subcharacters=findViewById(R.id.chatSubcharacters);model=findViewById(R.id.chatModel);adult=findViewById(R.id.chatAdult);style=findViewById(R.id.chatStyle);messages=findViewById(R.id.chatMessages);input=findViewById(R.id.chatInput);status=findViewById(R.id.chatStatus);character.setText(prefs.getString("character",""));personality.setText(prefs.getString("personality",""));subcharacters.setText(prefs.getString("subcharacters",""));adult.isChecked=prefs.getBoolean("adult",false);style.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,listOf("通常","日常会話","くだけた会話"));val cached=runCatching{JSONArray(secure.getString("model_cache","[]"))}.getOrNull();val ms=mutableListOf("openrouter/auto");if(cached!=null)for(i in 0 until cached.length()){val x=cached.optString(i);if(x.isNotBlank()&&!ms.contains(x))ms.add(x)};model.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,ms);findViewById<Button>(R.id.chatSay).setOnClickListener{send("say",false)};findViewById<Button>(R.id.chatDo).setOnClickListener{send("do",false)};findViewById<Button>(R.id.chatAuto).setOnClickListener{send("say",true)};findViewById<Button>(R.id.chatClear).setOnClickListener{prefs.edit().remove("history").apply();render()};render()}
 private fun history()=runCatching{JSONArray(prefs.getString("history","[]"))}.getOrDefault(JSONArray())
 private fun render(){messages.removeAllViews();val h=history();for(i in 0 until h.length()){val m=h.optJSONObject(i)?:continue;messages.addView(TextView(this).apply{setPadding(8,12,8,12);text=(if(m.optString("role")=="user")"あなた" else "キャラクター")+(if(m.optString("mode")=="do")"（行動）" else "")+"\n"+m.optString("content");setTextIsSelectable(true)})}}
 private fun castPrompt():String{val main=character.text.toString().trim().ifBlank{"キャラクター"};val p=personality.text.toString().trim();val lines=subcharacters.text.toString().lines().map{it.trim()}.filter{it.isNotBlank()};val b=StringBuilder("メインキャラクター #0: 名前「$main」");if(p.isNotBlank())b.append("、性格・設定「$p」");b.append("。");if(lines.isNotEmpty()){b.append("\nサブキャラクター:\n");lines.forEachIndexed{i,line->val parts=line.split("|",limit=2);val name=parts[0].trim().ifBlank{"サブキャラ${i+1}"};val setting=parts.getOrNull(1)?.trim().orEmpty();b.append("#${i+1}: 名前「$name」");if(setting.isNotBlank())b.append("、性格・設定「$setting」");b.append("\n")};b.append("同じ名前のキャラクターが複数いても統合せず、それぞれ別の個体として維持する。同一人物・コピー・分身という設定も許容し、各個体の発言と行動を混同しない。必要に応じて複数キャラクターを同じ場面に登場させる。複数人が話す場合は『名前(#番号): セリフ』の形式で話者を明示する。")};return b.toString()}
 private fun system():String{val st=style.selectedItemPosition;return "ロールプレイ会話をする。${castPrompt()} 説明役ではなく登場人物本人として自然な日本語で返答する。"+(if(st==1)"日常的で自然な口語を使う。" else if(st==2)"難語を避け、くだけた口語を使う。" else "")+(if(adult.isChecked)"利用者は18歳以上。成人同士の合意と安全を尊重した成人向け会話を許容する。未成年や非合意の性的内容は扱わない。" else "")}
 private fun send(mode:String,auto:Boolean){val text=if(auto)"会話の流れに沿って登場キャラクター側から自然に続きを返してください。" else input.text.toString().trim();if(text.isBlank())return;val key=secure.getString("openrouter_key","").orEmpty();if(key.isBlank()){status.text="小説生成画面でOpenRouter APIキーを保存してください。";return};prefs.edit().putString("character",character.text.toString()).putString("personality",personality.text.toString()).putString("subcharacters",subcharacters.text.toString()).putBoolean("adult",adult.isChecked).apply();val h=history();if(!auto){h.put(JSONObject().put("role","user").put("mode",mode).put("content",text));prefs.edit().putString("history",h.toString()).apply();input.setText("");render()};val msgs=JSONArray().put(JSONObject().put("role","system").put("content",system()));for(i in 0 until h.length()){val m=h.optJSONObject(i)?:continue;msgs.put(JSONObject().put("role",m.optString("role")).put("content",if(m.optString("mode")=="do")"[行動] ${m.optString("content")}" else m.optString("content")))};if(auto)msgs.put(JSONObject().put("role","user").put("content",text));val body=JSONObject().put("model",model.selectedItem?.toString()?:"openrouter/auto").put("messages",msgs).put("max_tokens",1200).toString().toRequestBody("application/json".toMediaType());status.text="生成中…";client.newCall(Request.Builder().url("https://openrouter.ai/api/v1/chat/completions").header("Authorization","Bearer $key").header("Content-Type","application/json").post(body).build()).enqueue(object:Callback{override fun onFailure(c:Call,e:IOException)=runOnUiThread{status.text="通信エラー: ${e.message}"};override fun onResponse(c:Call,r:Response){val d=runCatching{JSONObject(r.body?.string().orEmpty())}.getOrNull();val reply=d?.optJSONArray("choices")?.optJSONObject(0)?.optJSONObject("message")?.optString("content").orEmpty().trim();runOnUiThread{if(!r.isSuccessful||reply.isBlank()){status.text=d?.optJSONObject("error")?.optString("message")?.ifBlank{"AIから返信を取得できませんでした"}?:"AIから返信を取得できませんでした";return@runOnUiThread};val latest=history();latest.put(JSONObject().put("role","assistant").put("mode","say").put("content",reply));prefs.edit().putString("history",latest.toString()).apply();status.text="";render()}}})}
}