package com.novelsite.mobile
import android.os.Bundle
import android.net.Uri
import android.view.MotionEvent
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import androidx.security.crypto.EncryptedSharedPreferences
import androidx.security.crypto.MasterKey
import okhttp3.*
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONObject
import java.io.IOException
import java.util.concurrent.TimeUnit
class AiChatActivity:AppCompatActivity(){
 private val client=OkHttpClient.Builder().readTimeout(180,TimeUnit.SECONDS).build();private lateinit var character:EditText;private lateinit var personality:EditText;private lateinit var subcharacters:EditText;private lateinit var animeTitle:EditText;private lateinit var model:Spinner;private lateinit var adult:CheckBox;private lateinit var style:Spinner;private lateinit var length:Spinner;private lateinit var messages:LinearLayout;private lateinit var input:EditText;private lateinit var status:TextView
 private val prefs by lazy{getSharedPreferences("lexis_native_ai_chat",MODE_PRIVATE)};private val secure by lazy{val mk=MasterKey.Builder(this).setKeyScheme(MasterKey.KeyScheme.AES256_GCM).build();EncryptedSharedPreferences.create(this,"lexis_secure",mk,EncryptedSharedPreferences.PrefKeyEncryptionScheme.AES256_SIV,EncryptedSharedPreferences.PrefValueEncryptionScheme.AES256_GCM)}
 override fun onCreate(b:Bundle?){super.onCreate(b);setContentView(R.layout.activity_ai_chat);character=findViewById(R.id.chatCharacter);personality=findViewById(R.id.chatPersonality);subcharacters=findViewById(R.id.chatSubcharacters);animeTitle=findViewById(R.id.chatAnimeTitle);model=findViewById(R.id.chatModel);adult=findViewById(R.id.chatAdult);style=findViewById(R.id.chatStyle);length=findViewById(R.id.chatLength);messages=findViewById(R.id.chatMessages);input=findViewById(R.id.chatInput);status=findViewById(R.id.chatStatus);character.setText(prefs.getString("character",""));personality.setText(prefs.getString("personality",""));subcharacters.setText(prefs.getString("subcharacters",""));animeTitle.setText(prefs.getString("anime_title",""));adult.isChecked=prefs.getBoolean("adult",false);enableInnerScroll(personality);enableInnerScroll(subcharacters);enableInnerScroll(input);style.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,listOf("通常","日常会話","くだけた会話"));style.setSelection(prefs.getInt("style",0).coerceIn(0,2));length.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,listOf("短文","普通","長文"));length.setSelection(prefs.getInt("length",1).coerceIn(0,2));val cached=runCatching{JSONArray(secure.getString("model_cache","[]"))}.getOrNull();val ms=mutableListOf("openrouter/auto");if(cached!=null)for(i in 0 until cached.length()){val x=if(cached.opt(i) is JSONObject)cached.optJSONObject(i)?.optString("id").orEmpty() else cached.optString(i);if(x.isNotBlank()&&!ms.contains(x))ms.add(x)};model.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,ms);findViewById<Button>(R.id.chatAugmentMain).setOnClickListener{augmentMain()};findViewById<Button>(R.id.chatAugmentSubs).setOnClickListener{augmentSubs()};findViewById<Button>(R.id.chatSay).setOnClickListener{send("say",false)};findViewById<Button>(R.id.chatDo).setOnClickListener{send("do",false)};findViewById<Button>(R.id.chatAuto).setOnClickListener{send("say",true)};findViewById<Button>(R.id.chatClear).setOnClickListener{prefs.edit().remove("history").apply();render()};render()}
 private fun enableInnerScroll(v:EditText){v.setOnTouchListener{view,event->if(event.action==MotionEvent.ACTION_DOWN||event.action==MotionEvent.ACTION_MOVE)view.parent?.requestDisallowInterceptTouchEvent(true);if(event.action==MotionEvent.ACTION_UP||event.action==MotionEvent.ACTION_CANCEL)view.parent?.requestDisallowInterceptTouchEvent(false);false}}
 private fun saveSettings(){prefs.edit().putString("character",character.text.toString()).putString("personality",personality.text.toString()).putString("subcharacters",subcharacters.text.toString()).putString("anime_title",animeTitle.text.toString()).putBoolean("adult",adult.isChecked).putInt("style",style.selectedItemPosition).putInt("length",length.selectedItemPosition).apply()}
 private fun wikipediaQuery(name:String)=listOf(animeTitle.text.toString().trim(),name).filter{it.isNotBlank()}.joinToString(" ")
 private fun fetchWikipedia(name:String,done:(String)->Unit){val q=wikipediaQuery(name);val searchUrl="https://ja.wikipedia.org/w/api.php?action=query&list=search&srsearch=${Uri.encode(q)}&srlimit=3&format=json&utf8=1";client.newCall(Request.Builder().url(searchUrl).header("User-Agent","LexisAndroid/1.0 character-reference").get().build()).enqueue(object:Callback{override fun onFailure(c:Call,e:IOException)=done("");override fun onResponse(c:Call,r:Response){val d=runCatching{JSONObject(r.body?.string().orEmpty())}.getOrNull();val arr=d?.optJSONObject("query")?.optJSONArray("search");val title=arr?.optJSONObject(0)?.optString("title").orEmpty();if(title.isBlank()){done("");return};val extractUrl="https://ja.wikipedia.org/w/api.php?action=query&prop=extracts&explaintext=1&redirects=1&titles=${Uri.encode(title)}&format=json&formatversion=2";client.newCall(Request.Builder().url(extractUrl).header("User-Agent","LexisAndroid/1.0 character-reference").get().build()).enqueue(object:Callback{override fun onFailure(c2:Call,e:IOException)=done("");override fun onResponse(c2:Call,r2:Response){val x=runCatching{JSONObject(r2.body?.string().orEmpty())}.getOrNull()?.optJSONObject("query")?.optJSONArray("pages")?.optJSONObject(0)?.optString("extract").orEmpty();done(x.take(7000))}})}})}
 private fun parsePersonality(raw:String):String{var s=raw.trim();if(s.startsWith("```")){s=s.replace(Regex("^```(?:json)?\\s*"),"").replace(Regex("\\s*```$"),"").trim()};val json=runCatching{JSONObject(s)}.getOrNull();if(json!=null){val p=json.optString("personality").trim();if(p.isNotBlank())return p};return s}
 private fun augmentRequest(name:String,setting:String,done:(String)->Unit){val key=secure.getString("openrouter_key","").orEmpty();if(key.isBlank()){runOnUiThread{status.text="小説生成画面でOpenRouter APIキーを保存してください。"};return};fetchWikipedia(name){wiki->val title=animeTitle.text.toString().trim();val prompt="""キャラクター「$name」のロールプレイ用設定を日本語で作成してください。
作品名: ${title.ifBlank{"未指定"}}
既存のユーザー設定: ${setting.ifBlank{"なし"}}
Wikipedia取得情報: ${wiki.ifBlank{"取得できなかったため、モデルの既知情報を補助的に使用すること"}}

既存設定を尊重し、取得情報と確実に知っている作品情報を統合してください。不確かな内容は捏造しないでください。性格、口調、一人称、行動傾向、主要な関係性を、ロールプレイにそのまま使える簡潔な文章として返してください。前置きやMarkdown見出しは不要です。""";val msgs=JSONArray().put(JSONObject().put("role","system").put("content","あなたはアニメ・漫画・ゲーム等のキャラクター設定を整理する編集AIです。原作情報と推測を混同せず、日本語の設定文だけを返してください。")).put(JSONObject().put("role","user").put("content",prompt));val body=JSONObject().put("model",model.selectedItem?.toString()?:"openrouter/auto").put("messages",msgs).put("max_tokens",1200).toString().toRequestBody("application/json".toMediaType());client.newCall(Request.Builder().url("https://openrouter.ai/api/v1/chat/completions").header("Authorization","Bearer $key").header("Content-Type","application/json").header("X-Title","Lexis AI Chat Character Setup").post(body).build()).enqueue(object:Callback{override fun onFailure(c:Call,e:IOException)=runOnUiThread{status.text="設定取得エラー: ${e.message}"};override fun onResponse(c:Call,r:Response){val bodyText=r.body?.string().orEmpty();val d=runCatching{JSONObject(bodyText)}.getOrNull();val raw=d?.optJSONArray("choices")?.optJSONObject(0)?.optJSONObject("message")?.optString("content").orEmpty();val v=parsePersonality(raw);runOnUiThread{if(r.isSuccessful&&v.isNotBlank())done(v)else{val apiError=d?.optJSONObject("error")?.optString("message").orEmpty();status.text=if(apiError.isNotBlank())"設定取得エラー: $apiError" else "設定を取得できませんでした (HTTP ${r.code})"}}}})}}
 private fun augmentMain(){val n=character.text.toString().trim();if(n.isBlank()){status.text="メインキャラクター名を入力してください。";return};status.text="WikipediaとAIから設定を作成中…";augmentRequest(n,personality.text.toString()){personality.setText(it);personality.setSelection(0);saveSettings();status.text="メイン設定を自動取得しました。"}}
 private fun augmentSubs(){val lines=subcharacters.text.toString().lines().map{it.trim()}.filter{it.isNotBlank()};if(lines.isEmpty()){status.text="サブキャラクターを入力してください。";return};val out=MutableList(lines.size){""};fun next(i:Int){if(i>=lines.size){subcharacters.setText(out.joinToString("\n"));subcharacters.setSelection(0);saveSettings();status.text="サブキャラ設定を自動取得しました。";return};val p=lines[i].split("|",limit=2);val n=p[0].trim();val s=p.getOrNull(1)?.trim().orEmpty();status.text="${i+1}/${lines.size} $n の設定を作成中…";augmentRequest(n,s){v->out[i]="$n | $v";next(i+1)}};next(0)}
 private fun history()=runCatching{JSONArray(prefs.getString("history","[]"))}.getOrDefault(JSONArray())
 private fun render(){messages.removeAllViews();val h=history();for(i in 0 until h.length()){val m=h.optJSONObject(i)?:continue;messages.addView(TextView(this).apply{setPadding(8,12,8,12);text=(if(m.optString("role")=="user")"あなた" else "キャラクター")+(if(m.optString("mode")=="do")"（行動）" else "")+"\n"+m.optString("content");setTextIsSelectable(true)})}}
 private fun castPrompt():String{val main=character.text.toString().trim().ifBlank{"キャラクター"};val p=personality.text.toString().trim();val lines=subcharacters.text.toString().lines().map{it.trim()}.filter{it.isNotBlank()};val b=StringBuilder("メインキャラクター #0: 名前「$main」");if(p.isNotBlank())b.append("、性格・設定「$p」");b.append("。");if(lines.isNotEmpty()){b.append("\nサブキャラクター:\n");lines.forEachIndexed{i,line->val parts=line.split("|",limit=2);val name=parts[0].trim().ifBlank{"サブキャラ${i+1}"};val setting=parts.getOrNull(1)?.trim().orEmpty();b.append("#${i+1}: 名前「$name」");if(setting.isNotBlank())b.append("、性格・設定「$setting」");b.append("\n")};b.append("同じ名前のキャラクターが複数いても統合せず、それぞれ別の個体として維持する。同一人物・コピー・分身という設定も許容し、各個体の発言と行動を混同しない。必要に応じて複数キャラクターを同じ場面に登場させる。複数人が話す場合は『名前(#番号): セリフ』の形式で話者を明示する。")};return b.toString()}
 private fun lengthPrompt():String=when(length.selectedItemPosition){0->"返答は短文。原則1〜3文、会話のテンポを優先し、必要以上の説明や長い地の文を避ける。";2->"返答は長文。情景、表情、仕草、心理、会話の流れを丁寧に描写し、原則600〜1500文字程度を目安に十分な内容を書く。";else->"返答は普通の長さ。会話と必要な描写をバランスよく含め、原則200〜600文字程度を目安にする。"}
 private fun maxTokens():Int=when(length.selectedItemPosition){0->350;2->2200;else->1000}
 private fun system():String{val st=style.selectedItemPosition;return "ロールプレイ会話をする。${castPrompt()} ${lengthPrompt()} 説明役ではなく登場人物本人として自然な日本語で返答する。"+(if(st==1)"日常的で自然な口語を使う。" else if(st==2)"難語を避け、くだけた口語を使う。" else "")+(if(adult.isChecked)"利用者は18歳以上。成人同士の合意と安全を尊重した成人向け会話を許容する。未成年や非合意の性的内容は扱わない。" else "")}
 private fun send(mode:String,auto:Boolean){val text=if(auto)"会話の流れに沿って登場キャラクター側から自然に続きを返してください。" else input.text.toString().trim();if(text.isBlank())return;val key=secure.getString("openrouter_key","").orEmpty();if(key.isBlank()){status.text="小説生成画面でOpenRouter APIキーを保存してください。";return};saveSettings();val h=history();if(!auto){h.put(JSONObject().put("role","user").put("mode",mode).put("content",text));prefs.edit().putString("history",h.toString()).apply();input.setText("");render()};val msgs=JSONArray().put(JSONObject().put("role","system").put("content",system()));for(i in 0 until h.length()){val m=h.optJSONObject(i)?:continue;msgs.put(JSONObject().put("role",m.optString("role")).put("content",if(m.optString("mode")=="do")"[行動] ${m.optString("content")}" else m.optString("content")))};if(auto)msgs.put(JSONObject().put("role","user").put("content",text));val body=JSONObject().put("model",model.selectedItem?.toString()?:"openrouter/auto").put("messages",msgs).put("max_tokens",maxTokens()).toString().toRequestBody("application/json".toMediaType());status.text="生成中…";client.newCall(Request.Builder().url("https://openrouter.ai/api/v1/chat/completions").header("Authorization","Bearer $key").header("Content-Type","application/json").post(body).build()).enqueue(object:Callback{override fun onFailure(c:Call,e:IOException)=runOnUiThread{status.text="通信エラー: ${e.message}"};override fun onResponse(c:Call,r:Response){val d=runCatching{JSONObject(r.body?.string().orEmpty())}.getOrNull();val reply=d?.optJSONArray("choices")?.optJSONObject(0)?.optJSONObject("message")?.optString("content").orEmpty().trim();runOnUiThread{if(!r.isSuccessful||reply.isBlank()){status.text=d?.optJSONObject("error")?.optString("message")?.ifBlank{"AIから返信を取得できませんでした"}?:"AIから返信を取得できませんでした";return@runOnUiThread};val latest=history();latest.put(JSONObject().put("role","assistant").put("mode","say").put("content",reply));prefs.edit().putString("history",latest.toString()).apply();status.text="";render()}}})}
}