package com.novelsite.mobile

import android.content.ContentValues
import android.graphics.BitmapFactory
import android.os.Build
import android.os.Bundle
import android.provider.MediaStore
import android.util.Base64
import android.view.ViewGroup
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import androidx.security.crypto.EncryptedSharedPreferences
import androidx.security.crypto.MasterKey
import okhttp3.*
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.*
import java.io.IOException
import java.util.concurrent.TimeUnit

class ConsultationActivity:AppCompatActivity(){
 private val client=OkHttpClient.Builder().connectTimeout(30,TimeUnit.SECONDS).readTimeout(180,TimeUnit.SECONDS).build()
 private lateinit var model:Spinner;private lateinit var adult:CheckBox;private lateinit var thread:Spinner;private lateinit var messages:LinearLayout;private lateinit var input:EditText;private lateinit var status:TextView;private lateinit var send:Button;private lateinit var retry:EditText
 private val prefs by lazy{getSharedPreferences("lexis_consultation",MODE_PRIVATE)}
 private val secure by lazy{val mk=MasterKey.Builder(this).setKeyScheme(MasterKey.KeyScheme.AES256_GCM).build();EncryptedSharedPreferences.create(this,"lexis_secure",mk,EncryptedSharedPreferences.PrefKeyEncryptionScheme.AES256_SIV,EncryptedSharedPreferences.PrefValueEncryptionScheme.AES256_GCM)}
 override fun onCreate(b:Bundle?){super.onCreate(b);setContentView(R.layout.activity_consultation);model=findViewById(R.id.consultModel);adult=findViewById(R.id.consultAdult);thread=findViewById(R.id.consultThread);messages=findViewById(R.id.consultMessages);input=findViewById(R.id.consultInput);status=findViewById(R.id.consultStatus);send=findViewById(R.id.consultSend);retry=findViewById(R.id.consultRetryCount);retry.setText(prefs.getInt("retryCount",20).toString());retry.setOnFocusChangeListener{_,has->if(!has)prefs.edit().putInt("retryCount",retryCount()).apply()};val cached=runCatching{JSONArray(secure.getString("model_cache","[]"))}.getOrNull();val ms=mutableListOf("openrouter/auto");if(cached!=null)for(i in 0 until cached.length()){val item=cached.opt(i);val x=if(item is JSONObject)item.optString("id") else cached.optString(i);if(x.isNotBlank()&&!ms.contains(x))ms.add(x)};model.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,ms);val savedModel=prefs.getString("selected_model","openrouter/auto").orEmpty();val savedModelIndex=ms.indexOf(savedModel);if(savedModelIndex>=0)model.setSelection(savedModelIndex);model.onItemSelectedListener=object:AdapterView.OnItemSelectedListener{override fun onItemSelected(p:AdapterView<*>?,v:android.view.View?,pos:Int,id:Long){model.selectedItem?.toString()?.let{prefs.edit().putString("selected_model",it).apply()}};override fun onNothingSelected(p:AdapterView<*>?){}};adult.isChecked=prefs.getBoolean("adult",false);adult.setOnCheckedChangeListener{_,v->prefs.edit().putBoolean("adult",v).apply()};findViewById<Button>(R.id.consultNew).setOnClickListener{newThread()};thread.onItemSelectedListener=object:AdapterView.OnItemSelectedListener{override fun onItemSelected(p:AdapterView<*>?,v:android.view.View?,pos:Int,id:Long){render()};override fun onNothingSelected(p:AdapterView<*>?){}};send.setOnClickListener{prefs.edit().putInt("retryCount",retryCount()).apply();sendMessage()};refreshThreads()}
 private fun retryCount()=retry.text.toString().toIntOrNull()?.coerceIn(0,100)?:20
 private fun isCannedRefusal(s:String):Boolean{val x=s.replace(Regex("\\s+")," ");return listOf(Regex("申し訳ありませんが.*対応できません"),Regex("ご要望にお応えすることはできません"),Regex("露骨な性的行為.*(?:生成|描写).*(?:できません|対応できません)"),Regex("その(?:ため|内容).*お手伝いできません"),Regex("I(?:'m| am) sorry.*(?:can't|cannot).*assist",RegexOption.IGNORE_CASE),Regex("I can(?:not|'t) help with that",RegexOption.IGNORE_CASE)).any{it.containsMatchIn(x)}}
 private fun all():JSONArray=runCatching{JSONArray(prefs.getString("threads","[]"))}.getOrDefault(JSONArray())
 private fun save(a:JSONArray){prefs.edit().putString("threads",a.toString()).apply()}
 private fun newThread(){val a=all();val n=JSONObject().put("id",System.currentTimeMillis()).put("title","新しい相談").put("messages",JSONArray());val out=JSONArray().put(n);for(i in 0 until a.length())out.put(a.optJSONObject(i));save(out);refreshThreads(0)}
 private fun refreshThreads(sel:Int=0){val a=all();if(a.length()==0){newThread();return};val names=(0 until a.length()).map{a.optJSONObject(it)?.optString("title","新しい相談")?:"新しい相談"};thread.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,names);thread.setSelection(sel.coerceIn(0,names.lastIndex));render()}
 private fun current():JSONObject?=all().optJSONObject(thread.selectedItemPosition)
 private fun imageUrls(message:JSONObject?):JSONArray{val out=JSONArray();val a=message?.optJSONArray("images")?:return out;for(i in 0 until a.length()){val x=a.opt(i);val u=when(x){is JSONObject->x.optJSONObject("image_url")?.optString("url").orEmpty().ifBlank{x.optString("url")};is String->x;else->""};if(u.startsWith("data:image/")||u.startsWith("https://")||u.startsWith("http://"))out.put(u)};return out}
 private fun apiHistory(history:JSONArray):JSONArray{val out=JSONArray();for(i in 0 until history.length()){val m=history.optJSONObject(i)?:continue;val content=m.optString("content").trim();if(content.isBlank())continue;out.put(JSONObject().put("role",if(m.optString("role")=="assistant")"assistant" else "user").put("content",content))};return out}
 private fun imageBytes(url:String,done:(ByteArray,String)->Unit){if(url.startsWith("data:image/")){runCatching{val mime=url.substringAfter("data:").substringBefore(";");val bytes=Base64.decode(url.substringAfter("base64,"),Base64.DEFAULT);done(bytes,mime)}.onFailure{runOnUiThread{Toast.makeText(this,"画像データを読み込めませんでした",Toast.LENGTH_SHORT).show()}};return};client.newCall(Request.Builder().url(url).build()).enqueue(object:Callback{override fun onFailure(c:Call,e:IOException)=runOnUiThread{Toast.makeText(this@ConsultationActivity,"画像の取得に失敗しました",Toast.LENGTH_SHORT).show()};override fun onResponse(c:Call,r:Response){r.use{if(!it.isSuccessful)return;val bytes=it.body?.bytes()?:return;done(bytes,it.header("Content-Type")?.substringBefore(";")?:"image/png")}}})}
 private fun downloadImage(url:String){imageBytes(url){bytes,mime->try{val ext=if(mime.contains("jpeg"))"jpg" else if(mime.contains("webp"))"webp" else "png";val values=ContentValues().apply{put(MediaStore.Images.Media.DISPLAY_NAME,"Lexis-${System.currentTimeMillis()}.$ext");put(MediaStore.Images.Media.MIME_TYPE,mime);if(Build.VERSION.SDK_INT>=29)put(MediaStore.Images.Media.RELATIVE_PATH,"Pictures/Lexis")};val uri=contentResolver.insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,values)?:throw IOException("保存先を作成できません");contentResolver.openOutputStream(uri)?.use{it.write(bytes)}?:throw IOException("保存できません");runOnUiThread{Toast.makeText(this,"Pictures/Lexis に画像を保存しました",Toast.LENGTH_LONG).show()}}catch(e:Exception){runOnUiThread{Toast.makeText(this,"画像の保存に失敗しました: ${e.message}",Toast.LENGTH_LONG).show()}}}}
 private fun addImage(url:String){val iv=ImageView(this);iv.adjustViewBounds=true;iv.scaleType=ImageView.ScaleType.FIT_CENTER;iv.layoutParams=LinearLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT,ViewGroup.LayoutParams.WRAP_CONTENT).apply{topMargin=12};messages.addView(iv);val button=Button(this).apply{text="画像をダウンロード";setOnClickListener{downloadImage(url)}};messages.addView(button);imageBytes(url){bytes,_->val bm=BitmapFactory.decodeByteArray(bytes,0,bytes.size);runOnUiThread{iv.setImageBitmap(bm)}}}
 private fun render(){val n=current()?:return;messages.removeAllViews();val a=n.optJSONArray("messages")?:JSONArray();for(i in 0 until a.length()){val m=a.optJSONObject(i)?:continue;val tv=TextView(this);tv.text=(if(m.optString("role")=="user")"あなた\n" else "AI\n")+m.optString("content");tv.setTextColor(android.graphics.Color.BLACK);tv.setTextIsSelectable(true);tv.setPadding(0,8,0,8);messages.addView(tv);val imgs=m.optJSONArray("images")?:JSONArray();for(j in 0 until imgs.length())addImage(imgs.optString(j))}}
 private fun sendMessage(){val text=input.text.toString().trim();if(text.isBlank())return;val key=secure.getString("openrouter_key","").orEmpty().trim();if(key.isBlank()){status.text="小説生成画面でOpenRouter APIキーを保存してください。";return};val original=all();val idx=thread.selectedItemPosition;val n=original.optJSONObject(idx)?:return;val history=n.optJSONArray("messages")?:JSONArray();history.put(JSONObject().put("role","user").put("content",text));if(n.optString("title")=="新しい相談")n.put("title",text.replace("\n"," ").take(30));save(original);input.setText("");render();send.isEnabled=false;val msgs=JSONArray().put(JSONObject().put("role","system").put("content",systemPrompt()));val clean=apiHistory(history);for(i in 0 until clean.length())msgs.put(clean.getJSONObject(i));val tools=JSONArray().put(JSONObject().put("type","openrouter:image_generation"));val body=JSONObject().put("model",model.selectedItem?.toString()?:"openrouter/auto").put("messages",msgs).put("tools",tools).put("max_tokens",2048).toString().toRequestBody("application/json".toMediaType());val req=Request.Builder().url("https://openrouter.ai/api/v1/chat/completions").header("Authorization","Bearer $key").header("Content-Type","application/json").header("X-Title","Lexis AI Consultation").post(body).build();fun attempt(nAttempt:Int){status.text=if(nAttempt==0)"AIに相談中…" else "再試行中 $nAttempt/${retryCount()}";client.newCall(req).enqueue(object:Callback{override fun onFailure(c:Call,e:IOException)=runOnUiThread{send.isEnabled=true;status.text="通信エラー: ${e.message}"};override fun onResponse(c:Call,r:Response){val raw=r.body?.string().orEmpty();val parsed=runCatching{JSONObject(raw)};val data=parsed.getOrNull();val msg=data?.optJSONArray("choices")?.optJSONObject(0)?.optJSONObject("message");val answer=msg?.optString("content").orEmpty().trim();val images=imageUrls(msg);val refusal=isCannedRefusal(answer);val retryable=parsed.isFailure||(answer.isBlank()&&images.length()==0)||refusal;if(r.isSuccessful&&retryable&&nAttempt<retryCount()){runOnUiThread{attempt(nAttempt+1)};return};runOnUiThread{send.isEnabled=true;if(!r.isSuccessful){status.text=data?.optJSONObject("error")?.optString("message")?.ifBlank{"OpenRouter APIエラー"}?:"OpenRouter APIエラー";return@runOnUiThread};if(parsed.isFailure){status.text="再試行上限までJSON不正が続きました";return@runOnUiThread};if(answer.isBlank()&&images.length()==0){status.text="再試行上限まで空の返信が続きました";return@runOnUiThread};if(refusal){status.text="再試行上限まで定型的な拒否応答が続きました";return@runOnUiThread};val latest=all();val t=latest.optJSONObject(idx)?:return@runOnUiThread;val h=t.optJSONArray("messages")?:JSONArray().also{t.put("messages",it)};h.put(JSONObject().put("role","assistant").put("content",answer.ifBlank{"画像を生成しました。"}).put("images",images));save(latest);status.text="";render()}}})};attempt(0)}
 private fun systemPrompt():String{return if(adult.isChecked)"あなたは日本語のAI相談員です。利用者は18歳以上の成人です。恋愛、性、性生活、性的嗜好など成人の性的な相談も、必要以上に避けず、落ち着いて実用的に回答してください。画像を求められた場合は利用可能な画像生成ツールを使ってください。成人同士の合意、安全、プライバシーを尊重してください。未成年を性的に扱う内容や非合意の性的行為を肯定・促進しないでください。" else "あなたは日本語のAI相談員です。相談内容を整理し、共感的かつ具体的に回答してください。画像を求められた場合は利用可能な画像生成ツールを使ってください。医療・法律など高リスク分野では断定せず専門家への相談も案内してください。"}
}