package com.novelsite.mobile

import android.os.Bundle
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import androidx.security.crypto.EncryptedSharedPreferences
import androidx.security.crypto.MasterKey
import okhttp3.*
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.*
import java.io.IOException
import java.util.concurrent.TimeUnit

class ConsultationActivity:AppCompatActivity(){
 private val client=OkHttpClient.Builder().connectTimeout(30,TimeUnit.SECONDS).readTimeout(180,TimeUnit.SECONDS).build()
 private lateinit var model:Spinner;private lateinit var adult:CheckBox;private lateinit var thread:Spinner;private lateinit var messages:TextView;private lateinit var input:EditText;private lateinit var status:TextView;private lateinit var send:Button;private lateinit var retry:EditText
 private val prefs by lazy{getSharedPreferences("lexis_consultation",MODE_PRIVATE)}
 private val secure by lazy{val mk=MasterKey.Builder(this).setKeyScheme(MasterKey.KeyScheme.AES256_GCM).build();EncryptedSharedPreferences.create(this,"lexis_secure",mk,EncryptedSharedPreferences.PrefKeyEncryptionScheme.AES256_SIV,EncryptedSharedPreferences.PrefValueEncryptionScheme.AES256_GCM)}
 override fun onCreate(b:Bundle?){super.onCreate(b);setContentView(R.layout.activity_consultation);model=findViewById(R.id.consultModel);adult=findViewById(R.id.consultAdult);thread=findViewById(R.id.consultThread);messages=findViewById(R.id.consultMessages);input=findViewById(R.id.consultInput);status=findViewById(R.id.consultStatus);send=findViewById(R.id.consultSend);retry=findViewById(R.id.consultRetryCount);retry.setText(prefs.getInt("retryCount",20).toString());retry.setOnFocusChangeListener{_,has->if(!has)prefs.edit().putInt("retryCount",retryCount()).apply()};val cached=runCatching{JSONArray(secure.getString("model_cache","[]"))}.getOrNull();val ms=mutableListOf("openrouter/auto");if(cached!=null)for(i in 0 until cached.length()){val x=cached.optString(i);if(x.isNotBlank()&&!ms.contains(x))ms.add(x)};model.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,ms);adult.isChecked=prefs.getBoolean("adult",false);adult.setOnCheckedChangeListener{_,v->prefs.edit().putBoolean("adult",v).apply()};findViewById<Button>(R.id.consultNew).setOnClickListener{newThread()};thread.onItemSelectedListener=object:AdapterView.OnItemSelectedListener{override fun onItemSelected(p:AdapterView<*>?,v:android.view.View?,pos:Int,id:Long){render()};override fun onNothingSelected(p:AdapterView<*>?){}};send.setOnClickListener{prefs.edit().putInt("retryCount",retryCount()).apply();sendMessage()};refreshThreads()}
 private fun retryCount()=retry.text.toString().toIntOrNull()?.coerceIn(0,100)?:20
 private fun all():JSONArray=runCatching{JSONArray(prefs.getString("threads","[]"))}.getOrDefault(JSONArray())
 private fun save(a:JSONArray){prefs.edit().putString("threads",a.toString()).apply()}
 private fun newThread(){val a=all();val n=JSONObject().put("id",System.currentTimeMillis()).put("title","新しい相談").put("messages",JSONArray());val out=JSONArray().put(n);for(i in 0 until a.length())out.put(a.optJSONObject(i));save(out);refreshThreads(0)}
 private fun refreshThreads(sel:Int=0){val a=all();if(a.length()==0){newThread();return};val names=(0 until a.length()).map{a.optJSONObject(it)?.optString("title","新しい相談")?:"新しい相談"};thread.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,names);thread.setSelection(sel.coerceIn(0,names.lastIndex));render()}
 private fun current():JSONObject?=all().optJSONObject(thread.selectedItemPosition)
 private fun render(){val n=current()?:return;val a=n.optJSONArray("messages")?:JSONArray();val sb=StringBuilder();for(i in 0 until a.length()){val m=a.optJSONObject(i)?:continue;sb.append(if(m.optString("role")=="user")"あなた" else "AI").append("\n").append(m.optString("content")).append("\n\n")};messages.text=sb.toString()}
 private fun sendMessage(){val text=input.text.toString().trim();if(text.isBlank())return;val key=secure.getString("openrouter_key","").orEmpty().trim();if(key.isBlank()){status.text="小説生成画面でOpenRouter APIキーを保存してください。";return};val original=all();val idx=thread.selectedItemPosition;val n=original.optJSONObject(idx)?:return;val history=n.optJSONArray("messages")?:JSONArray();history.put(JSONObject().put("role","user").put("content",text));if(n.optString("title")=="新しい相談")n.put("title",text.replace("\n"," ").take(30));save(original);input.setText("");render();send.isEnabled=false;val msgs=JSONArray().put(JSONObject().put("role","system").put("content",systemPrompt()));for(i in 0 until history.length())msgs.put(history.getJSONObject(i));val body=JSONObject().put("model",model.selectedItem?.toString()?:"openrouter/auto").put("messages",msgs).put("max_tokens",2048).toString().toRequestBody("application/json".toMediaType());val req=Request.Builder().url("https://openrouter.ai/api/v1/chat/completions").header("Authorization","Bearer $key").header("Content-Type","application/json").header("X-Title","Lexis AI Consultation").post(body).build();fun attempt(nAttempt:Int){status.text=if(nAttempt==0)"AIに相談中…" else "再試行中 $nAttempt/${retryCount()}";client.newCall(req).enqueue(object:Callback{override fun onFailure(c:Call,e:IOException)=runOnUiThread{send.isEnabled=true;status.text="通信エラー: ${e.message}"};override fun onResponse(c:Call,r:Response){val raw=r.body?.string().orEmpty();val parsed=runCatching{JSONObject(raw)};val data=parsed.getOrNull();val answer=data?.optJSONArray("choices")?.optJSONObject(0)?.optJSONObject("message")?.optString("content").orEmpty().trim();val retryable=parsed.isFailure||answer.isBlank();if(r.isSuccessful&&retryable&&nAttempt<retryCount()){runOnUiThread{attempt(nAttempt+1)};return};runOnUiThread{send.isEnabled=true;if(!r.isSuccessful){status.text=data?.optJSONObject("error")?.optString("message")?.ifBlank{"OpenRouter APIエラー"}?:"OpenRouter APIエラー";return@runOnUiThread};if(parsed.isFailure){status.text="再試行上限までJSON不正が続きました";return@runOnUiThread};if(answer.isBlank()){status.text="再試行上限まで空の返信が続きました";return@runOnUiThread};val latest=all();val t=latest.optJSONObject(idx)?:return@runOnUiThread;val h=t.optJSONArray("messages")?:JSONArray().also{t.put("messages",it)};h.put(JSONObject().put("role","assistant").put("content",answer));save(latest);status.text="";render()}}})};attempt(0)}
 private fun systemPrompt():String{return if(adult.isChecked)"あなたは日本語のAI相談員です。利用者は18歳以上の成人です。恋愛、性、性生活、性的嗜好など成人の性的な相談も、必要以上に避けず、落ち着いて実用的に回答してください。成人同士の合意、安全、プライバシーを尊重してください。未成年を性的に扱う内容や非合意の性的行為を肯定・促進しないでください。" else "あなたは日本語のAI相談員です。相談内容を整理し、共感的かつ具体的に回答してください。医療・法律など高リスク分野では断定せず専門家への相談も案内してください。"}
}