package com.novelsite.mobile
import android.content.Intent
import android.net.Uri
import android.os.Bundle
import android.os.Environment
import android.content.ContentValues
import android.provider.MediaStore
import android.view.View
import android.view.MotionEvent
import android.text.method.ScrollingMovementMethod
import android.widget.*
import android.app.NotificationChannel
import android.app.NotificationManager
import androidx.core.app.NotificationCompat
import androidx.core.content.ContextCompat
import androidx.appcompat.app.AppCompatActivity
import androidx.documentfile.provider.DocumentFile
import androidx.security.crypto.EncryptedSharedPreferences
import androidx.security.crypto.MasterKey
import okhttp3.*
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONObject
import java.io.IOException
import java.util.concurrent.TimeUnit

class NovelGeneratorActivity:AppCompatActivity(){
 private val generationChannel="lexis_generation"
 private fun ensureGenerationChannel(){if(android.os.Build.VERSION.SDK_INT>=26){val m=getSystemService(NotificationManager::class.java);m.createNotificationChannel(NotificationChannel(generationChannel,"小説生成",NotificationManager.IMPORTANCE_DEFAULT))}}
 private fun notifyGenerationStarted(){ensureGenerationChannel();ContextCompat.startForegroundService(this,Intent(this,NovelGenerationService::class.java))}
 private fun notifyGenerationFinished(t:String){stopService(Intent(this,NovelGenerationService::class.java));ensureGenerationChannel();val open=android.app.PendingIntent.getActivity(this,0,Intent(this,NovelGeneratorActivity::class.java).addFlags(Intent.FLAG_ACTIVITY_SINGLE_TOP),android.app.PendingIntent.FLAG_UPDATE_CURRENT or android.app.PendingIntent.FLAG_IMMUTABLE);val m=getSystemService(NotificationManager::class.java);m.notify(4102,NotificationCompat.Builder(this,generationChannel).setSmallIcon(R.drawable.ic_lexis_with_pen).setContentTitle("Lexis 小説生成完了").setContentText(novelTitle(t)+" の生成が完了しました").setContentIntent(open).setAutoCancel(true).build())}
 private val defaultNovelTitle="Lexis生成小説"
 private fun novelTitle(v:String):String{val t=v.trim();return if(t.isBlank()||t=="無題"||t=="タイトル未設定"||t==defaultNovelTitle)defaultNovelTitle else t}
 private fun needsAiTitle(v:String)=v.trim().let{it.isBlank()||it=="無題"||it=="タイトル未設定"||it==defaultNovelTitle}
 private fun aiTitle(body:String,done:(String)->Unit){val excerpt=body.trim().take(12000);if(excerpt.isBlank())return done(defaultNovelTitle);call("次の小説本文に最もふさわしい日本語タイトルを1つだけ考えてください。タイトルだけを出力し、説明・引用符・括弧・『タイトル：』は付けないでください。\n\n"+excerpt){raw->val t=raw.lineSequence().firstOrNull{it.isNotBlank()}.orEmpty().trim().removePrefix("タイトル:").removePrefix("タイトル：").trim().trim('"','「','」','『','』');done(if(t.isBlank())defaultNovelTitle else t.take(100))}}
 private fun saveGeneratedNovel(body:String,r18:Boolean,done:()->Unit){val current=title.text.toString();if(!needsAiTitle(current)){saveNovelToLibrary(current,body,r18);done();return};busy(true,"タイトルを考えています…");aiTitle(body){t->title.setText(t);saveNovelToLibrary(t,body,r18);done()}}
 private fun cleanBlockMetaText(v:String)=v.lines().filterNot{line->line.trim().matches(Regex("""^[（(【\[]?\s*(?:第?\s*[0-9０-９一二三四五六七八九十百]+|次|次の)\s*ブロック\s*(?:へ|に)?\s*(?:続く|続きます|つづく|つづきます)\s*[）)】\]]?\s*[。.!！]?$"""))}.joinToString("\n").trim()
 private val client=OkHttpClient.Builder().connectTimeout(30,TimeUnit.SECONDS).readTimeout(180,TimeUnit.SECONDS).build()
 private lateinit var key:EditText; private lateinit var model:Spinner; private lateinit var title:EditText; private lateinit var genre:EditText
 private lateinit var chars:EditText; private lateinit var mood:EditText; private lateinit var prompt:EditText; private lateinit var adult:CheckBox
 private lateinit var blocks:EditText; private lateinit var tokens:EditText; private lateinit var result:EditText; private lateinit var progress:ProgressBar; private lateinit var status:TextView
 private lateinit var email:EditText; private lateinit var password:EditText; private lateinit var blockPromptContainer:LinearLayout; private lateinit var retryCount:EditText
 private lateinit var generationPanel:LinearLayout; private lateinit var libraryPanel:LinearLayout; private lateinit var libraryContainer:LinearLayout; private lateinit var templateName:EditText; private lateinit var templateSpinner:Spinner
 private var downloadNovel:JSONObject?=null
 private val prefs by lazy{val mk=MasterKey.Builder(this).setKeyScheme(MasterKey.KeyScheme.AES256_GCM).build();EncryptedSharedPreferences.create(this,"lexis_secure",mk,EncryptedSharedPreferences.PrefKeyEncryptionScheme.AES256_SIV,EncryptedSharedPreferences.PrefValueEncryptionScheme.AES256_GCM)}
 override fun onCreate(b:Bundle?){super.onCreate(b);setContentView(R.layout.activity_novel_generator)
  key=findViewById(R.id.apiKey);model=findViewById(R.id.modelSpinner);title=findViewById(R.id.titleInput);genre=findViewById(R.id.genreInput);chars=findViewById(R.id.charactersInput);mood=findViewById(R.id.moodInput);prompt=findViewById(R.id.instructionInput);adult=findViewById(R.id.r18Check);blocks=findViewById(R.id.blockCount);tokens=findViewById(R.id.maxTokens);result=findViewById(R.id.resultText);progress=findViewById(R.id.progress);status=findViewById(R.id.status);email=findViewById(R.id.lexisEmail);password=findViewById(R.id.lexisPassword);blockPromptContainer=findViewById(R.id.blockPromptContainer);retryCount=findViewById(R.id.retryCount);generationPanel=findViewById(R.id.generationPanel);libraryPanel=findViewById(R.id.libraryPanel);libraryContainer=findViewById(R.id.libraryContainer);templateName=findViewById(R.id.templateName);templateSpinner=findViewById(R.id.templateSpinner)
  val storedKey=prefs.getString("openrouter_key","").orEmpty()
  val fileKey=readPersistentApiKey()
  val restoredKey=storedKey.ifBlank{fileKey}
  key.setText(restoredKey)
  if(storedKey.isBlank()&&restoredKey.isNotBlank())prefs.edit().putString("openrouter_key",restoredKey).apply()
  adult.isChecked=prefs.getBoolean("r18_enabled",false)
  val cachedModels=runCatching{JSONArray(prefs.getString("model_cache","[]")).let{a->(0 until a.length()).mapNotNull{i->a.optString(i).takeIf{v->v.isNotBlank()}}}}.getOrDefault(emptyList())
  setModels(cachedModels.ifEmpty{listOf("openrouter/auto")}); addBlockPrompt(); addBlockPrompt(); addBlockPrompt()
  enableTextEditing(key);enableTextEditing(templateName);enableTextEditing(title);enableTextEditing(genre);enableTextEditing(chars);enableTextEditing(mood);enableTextEditing(prompt);enableTextEditing(blocks);enableTextEditing(tokens);enableTextEditing(retryCount);enableTextEditing(email);enableTextEditing(password);enableTextEditing(result)
  result.movementMethod=ScrollingMovementMethod.getInstance()
  result.setOnTouchListener{v,e->
   if(e.action==MotionEvent.ACTION_DOWN||e.action==MotionEvent.ACTION_MOVE)v.parent?.requestDisallowInterceptTouchEvent(true)
   if(e.action==MotionEvent.ACTION_UP||e.action==MotionEvent.ACTION_CANCEL)v.parent?.requestDisallowInterceptTouchEvent(false)
   false
  }
  findViewById<Button>(R.id.navGenerate).setOnClickListener{showGenerator()};findViewById<Button>(R.id.navLibrary).setOnClickListener{showLibrary()}
  findViewById<Button>(R.id.addBlockPrompt).setOnClickListener{addBlockPrompt()}
  findViewById<Button>(R.id.openRouterKeyPage).setOnClickListener{startActivity(Intent(Intent.ACTION_VIEW,Uri.parse("https://openrouter.ai/settings/keys")))}
  refreshTemplates()
  findViewById<Button>(R.id.saveTemplate).setOnClickListener{saveTemplate()}
  findViewById<Button>(R.id.loadTemplate).setOnClickListener{loadSelectedTemplate()}
  findViewById<Button>(R.id.saveApiKey).setOnClickListener{val v=key.text.toString().trim();prefs.edit().putString("openrouter_key",v).apply();persistApiKey(v);toast("APIキーを保存しました")}
  adult.setOnCheckedChangeListener{_,checked->prefs.edit().putBoolean("r18_enabled",checked).apply()}
  model.onItemSelectedListener=object:AdapterView.OnItemSelectedListener{override fun onItemSelected(parent:AdapterView<*>?,view:View?,position:Int,id:Long){prefs.edit().putString("selected_model",model.selectedItem?.toString()?:"openrouter/auto").apply()};override fun onNothingSelected(parent:AdapterView<*>?){}}
  findViewById<Button>(R.id.loadModels).setOnClickListener{loadModels()};findViewById<Button>(R.id.generate).setOnClickListener{generate(false)};findViewById<Button>(R.id.generateBlocks).setOnClickListener{generate(true)}
  findViewById<Button>(R.id.continueButton).setOnClickListener{continueStory()};findViewById<Button>(R.id.saveDraft).setOnClickListener{saveDraft()};findViewById<Button>(R.id.shareText).setOnClickListener{share()};findViewById<Button>(R.id.uploadLexis).setOnClickListener{loginUpload()}
 }
 private fun templatePrefs()=getSharedPreferences("lexis_templates",MODE_PRIVATE)
 private fun loadTemplates():JSONArray=runCatching{JSONArray(templatePrefs().getString("templates","[]"))}.getOrDefault(JSONArray())
 private fun refreshTemplates(){val a=loadTemplates();val names=mutableListOf("テンプレートを選択");for(i in 0 until a.length())names.add(a.optJSONObject(i)?.optString("name").orEmpty().ifBlank{"テンプレート "+(i+1)});templateSpinner.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,names)}
 private fun saveTemplate(){val name=templateName.text.toString().trim();if(name.isBlank())return toast("テンプレート名を入力してください");val plans=JSONArray();blockPrompts().forEach{plans.put(it)};val item=JSONObject().put("name",name).put("model",m()).put("title",title.text.toString()).put("genre",genre.text.toString()).put("characters",chars.text.toString()).put("mood",mood.text.toString()).put("prompt",prompt.text.toString()).put("r18",adult.isChecked).put("blocks",blocks.text.toString()).put("tokens",tokens.text.toString()).put("retryCount",retryCount.text.toString()).put("blockPrompts",plans);val old=loadTemplates();val out=JSONArray();out.put(item);for(i in 0 until old.length()){val x=old.optJSONObject(i)?:continue;if(!x.optString("name").equals(name,true))out.put(x)};templatePrefs().edit().putString("templates",out.toString()).apply();refreshTemplates();templateSpinner.setSelection(1);toast("テンプレート「"+name+"」を保存しました")}
 private fun loadSelectedTemplate(){val pos=templateSpinner.selectedItemPosition;if(pos<=0)return toast("テンプレートを選択してください");val x=loadTemplates().optJSONObject(pos-1)?:return toast("テンプレートを読み込めませんでした");title.setText(x.optString("title"));genre.setText(x.optString("genre"));chars.setText(x.optString("characters"));mood.setText(x.optString("mood"));prompt.setText(x.optString("prompt"));adult.isChecked=x.optBoolean("r18",adult.isChecked);blocks.setText(x.optString("blocks","3"));tokens.setText(x.optString("tokens","2000"));retryCount.setText(x.optString("retryCount","20"));val plans=x.optJSONArray("blockPrompts")?:JSONArray();blockPromptContainer.removeAllViews();if(plans.length()==0){addBlockPrompt();addBlockPrompt();addBlockPrompt()}else for(i in 0 until plans.length())addBlockPrompt().also{(blockPromptContainer.getChildAt(i) as EditText).setText(plans.optString(i))};val wanted=x.optString("model");val items=(0 until model.adapter.count).map{model.adapter.getItem(it).toString()};val mp=items.indexOf(wanted);if(mp>=0)model.setSelection(mp);toast("テンプレート「"+x.optString("name")+"」を読み込みました")}
 private fun enableTextEditing(v:EditText){v.isLongClickable=true;v.setTextIsSelectable(true);v.customSelectionActionModeCallback=null;v.customInsertionActionModeCallback=null}
 private fun showGenerator(){generationPanel.visibility=View.VISIBLE;libraryPanel.visibility=View.GONE}
 private fun showLibrary(){generationPanel.visibility=View.GONE;libraryPanel.visibility=View.VISIBLE;renderLibrary()}
 private fun libraryPrefs()=getSharedPreferences("lexis_novel_library",MODE_PRIVATE)
 private fun loadLibrary():JSONArray=runCatching{JSONArray(libraryPrefs().getString("novels","[]"))}.getOrDefault(JSONArray())
 private fun saveNovelToLibrary(t:String,body:String,r18:Boolean){if(body.isBlank())return;val a=loadLibrary();val n=JSONObject().put("id",System.currentTimeMillis()).put("title",novelTitle(t)).put("body",body).put("r18",r18).put("savedAt",System.currentTimeMillis());val out=JSONArray().put(n);for(i in 0 until a.length())out.put(a.getJSONObject(i));libraryPrefs().edit().putString("novels",out.toString()).apply();persistNovelFile(n.optLong("id"),n.optString("title"),body)}
 private fun persistNovelFile(id:Long,t:String,body:String){runCatching{val values=ContentValues().apply{put(MediaStore.Downloads.DISPLAY_NAME,safeName(novelTitle(t))+"_"+id+".txt");put(MediaStore.Downloads.MIME_TYPE,"text/plain");put(MediaStore.Downloads.RELATIVE_PATH,Environment.DIRECTORY_DOCUMENTS+"/Lexis/小説")};val uri=contentResolver.insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI,values)?:return;contentResolver.openOutputStream(uri)?.bufferedWriter(Charsets.UTF_8)?.use{it.write(body)}}}
 private fun setLibraryBookmark(id:Long,on:Boolean){val a=loadLibrary();for(i in 0 until a.length()){val n=a.optJSONObject(i)?:continue;if(n.optLong("id")==id){n.put("bookmarked",on);break}};libraryPrefs().edit().putString("novels",a.toString()).apply()}
 private fun deleteLibraryNovel(id:Long){val a=loadLibrary();val out=JSONArray();for(i in 0 until a.length()){val n=a.getJSONObject(i);if(n.optLong("id")!=id)out.put(n)};libraryPrefs().edit().putString("novels",out.toString()).apply();toast("削除しました");renderLibrary()}
 private fun replaceUntitledLibraryNovels(){val a=loadLibrary();val targets=(0 until a.length()).filter{i->needsAiTitle(a.optJSONObject(i)?.optString("title","").orEmpty())};if(targets.isEmpty())return toast("置き換える無題タイトルはありません");if(k().isBlank())return toast("OpenRouter APIキーを入力してください");fun next(pos:Int,changed:Int){if(pos>=targets.size){libraryPrefs().edit().putString("novels",a.toString()).apply();toast(changed.toString()+"件のタイトルをAIで付け直しました");renderLibrary();busy(false,"タイトル付け完了");return};val i=targets[pos];val n=a.optJSONObject(i)?:return next(pos+1,changed);busy(true,"タイトルを考えています "+(pos+1)+" / "+targets.size);aiTitle(n.optString("body","")){t->n.put("title",t);n.put("savedAt",System.currentTimeMillis());libraryPrefs().edit().putString("novels",a.toString()).apply();persistNovelFile(n.optLong("id"),t,n.optString("body",""));renderLibrary();next(pos+1,changed+1)}};next(0,0)}
 private fun updateLibraryNovel(id:Long,t:String,body:String){val a=loadLibrary();for(i in 0 until a.length()){val n=a.getJSONObject(i);if(n.optLong("id")==id){n.put("title",novelTitle(t));n.put("body",body);n.put("savedAt",System.currentTimeMillis());break}};libraryPrefs().edit().putString("novels",a.toString()).apply();persistNovelFile(id,t,body)}
 private fun renderLibrary(){libraryContainer.removeAllViews();val importButton=Button(this).apply{text="小説フォルダから読み込む";isAllCaps=false;setOnClickListener{startActivityForResult(Intent(Intent.ACTION_OPEN_DOCUMENT_TREE).apply{addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION or Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION)},9002)}};libraryContainer.addView(importButton);libraryContainer.addView(Button(this).apply{text="無題タイトルを置き換える";isAllCaps=false;setOnClickListener{replaceUntitledLibraryNovels()}});val a=loadLibrary();if(a.length()==0){libraryContainer.addView(TextView(this).apply{text="小説はまだありません"});return};for(i in 0 until a.length()){val n=a.getJSONObject(i);val row=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL};val star=Button(this).apply{text=if(n.optBoolean("bookmarked",false))"★" else "☆";textSize=22f;isAllCaps=false;setOnClickListener{val on=!n.optBoolean("bookmarked",false);n.put("bookmarked",on);setLibraryBookmark(n.optLong("id"),on);text=if(on)"★" else "☆";toast(if(on)"ブックマークしました" else "ブックマークを解除しました")}};val item=Button(this).apply{text=novelTitle(n.optString("title",""));isAllCaps=false;layoutParams=LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.WRAP_CONTENT,1f);setOnClickListener{renderNovelDetail(n)}};row.addView(star);row.addView(item);libraryContainer.addView(row)}}
 private fun renderNovelDetail(n:JSONObject){libraryContainer.removeAllViews();libraryContainer.addView(Button(this).apply{text="← 一覧へ戻る";setOnClickListener{renderLibrary()}});val bookmark=Button(this).apply{text=if(n.optBoolean("bookmarked",false))"★ ブックマーク済み" else "☆ ブックマーク";isAllCaps=false;setOnClickListener{val on=!n.optBoolean("bookmarked",false);n.put("bookmarked",on);setLibraryBookmark(n.optLong("id"),on);text=if(on)"★ ブックマーク済み" else "☆ ブックマーク";toast(if(on)"ブックマークしました" else "ブックマークを解除しました")}};libraryContainer.addView(bookmark);val t=EditText(this).apply{setText(novelTitle(n.optString("title","")));isEnabled=false;enableTextEditing(this)};val body=EditText(this).apply{setText(n.optString("body",""));minLines=16;gravity=android.view.Gravity.TOP;isEnabled=false;enableTextEditing(this)};libraryContainer.addView(t);libraryContainer.addView(body);val edit=Button(this).apply{text="編集"};val save=Button(this).apply{text="編集を保存";visibility=View.GONE};val cancel=Button(this).apply{text="キャンセル";visibility=View.GONE};edit.setOnClickListener{t.isEnabled=true;body.isEnabled=true;edit.visibility=View.GONE;save.visibility=View.VISIBLE;cancel.visibility=View.VISIBLE;t.requestFocus()};save.setOnClickListener{updateLibraryNovel(n.optLong("id"),t.text.toString(),body.text.toString());n.put("title",novelTitle(t.text.toString()));n.put("body",body.text.toString());t.isEnabled=false;body.isEnabled=false;edit.visibility=View.VISIBLE;save.visibility=View.GONE;cancel.visibility=View.GONE;toast("編集を保存しました")};cancel.setOnClickListener{t.setText(n.optString("title",""));body.setText(n.optString("body",""));t.isEnabled=false;body.isEnabled=false;edit.visibility=View.VISIBLE;save.visibility=View.GONE;cancel.visibility=View.GONE};libraryContainer.addView(edit);libraryContainer.addView(save);libraryContainer.addView(cancel);libraryContainer.addView(Button(this).apply{text="Lexis投稿";setOnClickListener{title.setText(t.text);result.setText(body.text);showGenerator();toast("Lexisログイン情報を確認して投稿してください")}});libraryContainer.addView(Button(this).apply{text="ダウンロード";setOnClickListener{downloadNovel=n;startActivityForResult(Intent(Intent.ACTION_CREATE_DOCUMENT).apply{type="text/plain";putExtra(Intent.EXTRA_TITLE,safeName(t.text.toString())+".txt")},9001)}});libraryContainer.addView(Button(this).apply{text="削除";setOnClickListener{deleteLibraryNovel(n.optLong("id"))}})}
 override fun onActivityResult(requestCode:Int,resultCode:Int,data:Intent?){super.onActivityResult(requestCode,resultCode,data);if(resultCode!=RESULT_OK)return;if(requestCode==9001){val uri=data?.data?:return;val n=downloadNovel?:return;runCatching{contentResolver.openOutputStream(uri)?.bufferedWriter(Charsets.UTF_8)?.use{it.write(n.optString("body",""))}}.onSuccess{toast("ダウンロードしました")}.onFailure{toast("保存失敗: "+it.message)}}else if(requestCode==9002){val uri=data?.data?:return;runCatching{contentResolver.takePersistableUriPermission(uri,Intent.FLAG_GRANT_READ_URI_PERMISSION)};val dir=DocumentFile.fromTreeUri(this,uri)?:return toast("フォルダを開けませんでした");val apiFile=dir.listFiles().firstOrNull{it.isFile&&it.name.equals("apikey.txt",ignoreCase=true)};val restoredApiKey=apiFile?.let{file->runCatching{contentResolver.openInputStream(file.uri)?.bufferedReader(Charsets.UTF_8)?.use{it.readText().trim()}.orEmpty()}.getOrDefault("")}.orEmpty();if(restoredApiKey.isNotBlank()){key.setText(restoredApiKey);prefs.edit().putString("openrouter_key",restoredApiKey).apply()};val old=loadLibrary();val out=JSONArray();for(i in 0 until old.length())out.put(old.getJSONObject(i));var imported=0;dir.listFiles().filter{it.isFile&&it.name?.lowercase()?.endsWith(".txt")==true&&it.name?.equals("apikey.txt",ignoreCase=true)!=true}.forEach{file->val body=runCatching{contentResolver.openInputStream(file.uri)?.bufferedReader(Charsets.UTF_8)?.use{it.readText()}.orEmpty()}.getOrDefault("");if(body.isBlank())return@forEach;val exists=(0 until out.length()).any{i->out.getJSONObject(i).optString("body")==body};if(!exists){val fileTitle=file.name?.substringBeforeLast('.')?.replace(Regex("_[0-9]{10,}$"),"").orEmpty();out.put(JSONObject().put("id",System.currentTimeMillis()+imported).put("title",novelTitle(fileTitle)).put("body",body).put("r18",false).put("savedAt",file.lastModified().takeIf{it>0}?:System.currentTimeMillis()));imported++}};libraryPrefs().edit().putString("novels",out.toString()).apply();val keyMessage=if(restoredApiKey.isNotBlank())" / APIキーも復元しました" else " / apikey.txt は見つかりませんでした";toast(imported.toString()+"件の小説を読み込みました"+keyMessage);renderLibrary()}}
 private fun persistApiKey(v:String){if(v.isBlank())return;runCatching{val values=ContentValues().apply{put(MediaStore.Downloads.DISPLAY_NAME,"apikey.txt");put(MediaStore.Downloads.MIME_TYPE,"text/plain");put(MediaStore.Downloads.RELATIVE_PATH,Environment.DIRECTORY_DOCUMENTS+"/Lexis/小説")};val uri=contentResolver.insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI,values)?:return;contentResolver.openOutputStream(uri)?.bufferedWriter(Charsets.UTF_8)?.use{it.write(v)}}}
 private fun readPersistentApiKey():String=""
 private fun safeName(v:String)=v.replace(Regex("[\\/:*?\"<>|]"),"_").take(80)
 private fun setModels(x:List<String>){val items=x.distinct().ifEmpty{listOf("openrouter/auto")};model.adapter=ArrayAdapter(this,android.R.layout.simple_spinner_dropdown_item,items);val saved=prefs.getString("selected_model","openrouter/auto").orEmpty();val pos=items.indexOf(saved);if(pos>=0)model.setSelection(pos)}
 private fun loadModels(){if(k().isBlank())return toast("APIキーを入力してください");busy(true,"モデル取得中...");Thread{try{val req=Request.Builder().url("https://openrouter.ai/api/v1/models").header("Authorization","Bearer ${k()}").build();client.newCall(req).execute().use{r->if(!r.isSuccessful)throw IOException("HTTP ${r.code}");val a=JSONObject(r.body!!.string()).getJSONArray("data");val x=(0 until a.length()).map{a.getJSONObject(it).getString("id")}.sorted();runOnUiThread{val items=x.ifEmpty{listOf("openrouter/auto")};prefs.edit().putString("model_cache",JSONArray(items).toString()).apply();setModels(items);busy(false,x.size.toString()+"モデル取得")}}}catch(e:Exception){runOnUiThread{busy(false,"失敗: ${e.message}")}}}.start()}
 private fun addBlockPrompt(){val e=EditText(this).apply{hint="第${blockPromptContainer.childCount+1}ブロックの内容";minLines=2;gravity=android.view.Gravity.TOP;inputType=android.text.InputType.TYPE_CLASS_TEXT or android.text.InputType.TYPE_TEXT_FLAG_MULTI_LINE;enableTextEditing(this)};e.setOnEditorActionListener{_,_,_->false};blockPromptContainer.addView(e)}
 private fun blockPrompts()=(0 until blockPromptContainer.childCount).mapNotNull{(blockPromptContainer.getChildAt(it) as? EditText)?.text?.toString()?.trim()}
 private fun k()=key.text.toString().trim();private fun m()=model.selectedItem?.toString()?.trim().orEmpty().ifBlank{"openrouter/auto"}
 private fun base(extra:String="")="""小説本文だけを出力してください。メタ説明は禁止。タイトル:${title.text}\nジャンル:${genre.text}\n登場人物:${chars.text}\n雰囲気:${mood.text}\n指示:${prompt.text}\n${if(adult.isChecked)"R18。登場人物は全員18歳以上の成人で、性的関係は明確な合意があるもののみ。" else ""}\n$extra"""
 private fun generate(multi:Boolean){if(k().isBlank())return toast("APIキーを入力してください");if(prompt.text.isBlank())return toast("生成指示を入力してください");notifyGenerationStarted();if(!multi){busy(true,"生成中...");call(base()){result.setText(it);saveGeneratedNovel(it,adult.isChecked){busy(false,"生成完了");notifyGenerationFinished(title.text.toString())}}}else{val plans=blockPrompts();val count=maxOf(2,blocks.text.toString().toIntOrNull()?:plans.size.coerceAtLeast(3));val out=mutableListOf<String>();fun next(i:Int){if(i>=count){val all=out.joinToString("\n\n");result.setText(all);saveGeneratedNovel(all,adult.isChecked){busy(false,"ブロック生成完了");notifyGenerationFinished(title.text.toString())};return};busy(true,"ブロック ${i+1}/$count 生成中...");val plan=plans.getOrNull(i).orEmpty();val prev=out.takeLast(2).joinToString("\n\n");call(base("全$count ブロック中の第${i+1}ブロック。今回の展開:$plan\n直前までの本文:$prev\nこのブロックの本文のみを書き、末尾に『第○ブロックへ続く』『次のブロックへ続く』等の進行管理文は絶対に出力しない。")){out+=cleanBlockMetaText(it);result.setText(out.joinToString("\n\n"));next(i+1)}};next(0)}}
 private fun continueStory(){val old=result.text.toString();if(old.isBlank())return toast("本文がありません");notifyGenerationStarted();call(base("以下の本文から自然に続きを書いてください:\n"+old.takeLast(10000))){result.setText(old+"\n\n"+it);saveGeneratedNovel(result.text.toString(),adult.isChecked){busy(false,"続きを生成しました");notifyGenerationFinished(title.text.toString())}}}
 private fun call(p:String,done:(String)->Unit){busy(true,"AI応答待ち...");val body=JSONObject().put("model",m()).put("messages",JSONArray().put(JSONObject().put("role","user").put("content",p))).put("max_tokens",tokens.text.toString().toIntOrNull()?:2000).toString().toRequestBody("application/json".toMediaType());val req=Request.Builder().url("https://openrouter.ai/api/v1/chat/completions").header("Authorization","Bearer ${k()}").header("HTTP-Referer","https://shosetsu-toukou-site.org").header("X-Title","Lexis Android Novel").post(body).build();val maxRetry=retryCount.text.toString().toIntOrNull()?.coerceIn(0,100)?:20;fun attempt(n:Int){client.newCall(req).enqueue(object:Callback{override fun onFailure(c:Call,e:IOException){if(n<maxRetry){attempt(n+1)}else runOnUiThread{busy(false,"通信失敗: ${e.message}")}};override fun onResponse(c:Call,r:Response){r.use{if(!r.isSuccessful){if(n<maxRetry){attempt(n+1);return}else return runOnUiThread{busy(false,"API失敗 HTTP ${r.code}")}};val raw=runCatching{JSONObject(r.body!!.string()).getJSONArray("choices").getJSONObject(0).getJSONObject("message").optString("content","")}.getOrDefault("");val text=if(raw.trim().equals("null",true))"" else raw.trim();if(text.isBlank()&&n<maxRetry){attempt(n+1);return};runOnUiThread{if(text.isBlank())busy(false,"空の応答でした") else done(text)}}}})};attempt(0)}
 private fun saveDraft(){saveNovelToLibrary(title.text.toString(),result.text.toString(),adult.isChecked);toast("端末に保存しました")}
 private fun share(){val i=Intent(Intent.ACTION_SEND).apply{type="text/plain";putExtra(Intent.EXTRA_SUBJECT,novelTitle(title.text.toString()));putExtra(Intent.EXTRA_TEXT,result.text.toString())};startActivity(Intent.createChooser(i,"小説を共有"))}
 private fun loginUpload(){toast("Lexis投稿処理を開始します")}
 private fun busy(on:Boolean,msg:String){progress.visibility=if(on)View.VISIBLE else View.GONE;status.text=msg}
 private fun toast(v:String)=Toast.makeText(this,v,Toast.LENGTH_LONG).show()
}