const $=id=>document.getElementById(id),KEY="lexis_native_ai_chat_v1",CFG="lexis_native_ai_chat_characters_v2",BACKEND="https://shosetsu-toukou-site.org";let history=[];
function esc(s){return String(s||"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
function load(){try{history=JSON.parse(localStorage.getItem(KEY)||"[]")}catch{history=[]};try{const c=JSON.parse(localStorage.getItem(CFG)||"{}");if(c.character)$("character").value=c.character;if(c.personality)$("personality").value=c.personality;if(c.subcharacters)$("subcharacters").value=c.subcharacters;if(c.animeTitle)$("animeTitle").value=c.animeTitle}catch{}render()}
function save(){localStorage.setItem(KEY,JSON.stringify(history));localStorage.setItem(CFG,JSON.stringify({character:$("character").value,personality:$("personality").value,subcharacters:$("subcharacters").value,animeTitle:$("animeTitle").value}))}
function subcharacters(){return $("subcharacters").value.split(/\r?\n/).map((line,i)=>{const x=line.trim();if(!x)return null;const p=x.split("|");return{id:i+1,name:(p.shift()||"").trim()||`サブキャラ${i+1}`,personality:p.join("|").trim()}}).filter(Boolean)}
async function augmentCharacter(name,personality){if(!name.trim())throw new Error("キャラクター名を入力してください");const s=await window.lexis.getSettings();const r=await fetch(BACKEND+"/api/ai/chat/character/augment",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({character_name:name.trim(),personality:(personality||"").trim()||null,anime_title:$("animeTitle").value.trim()||null,model:$("model").value||s.model||null})});const d=await r.json();if(!r.ok)throw new Error(d?.detail||`設定取得エラー ${r.status}`);return d}
async function augmentMain(){$("status").textContent="Wikipedia・pixiv百科事典などからメインキャラを調査中…";try{const d=await augmentCharacter($("character").value,$("personality").value);$("personality").value=d.enriched_personality||$("personality").value;save();$("status").textContent=`設定を取得しました${d.used_search?"（Web参照あり）":""}`;}catch(e){$("status").textContent=e.message||String(e)}}
async function augmentSubs(){const subs=subcharacters();if(!subs.length){$("status").textContent="サブキャラクターを入力してください。";return}$("status").textContent=`サブキャラ ${subs.length}人を調査中…`;const out=[];try{for(let i=0;i<subs.length;i++){const x=subs[i];$("status").textContent=`${i+1}/${subs.length} ${x.name} を調査中…`;const d=await augmentCharacter(x.name,x.personality);out.push(`${x.name} | ${d.enriched_personality||x.personality}`)}$("subcharacters").value=out.join("\n");save();$("status").textContent="サブキャラ設定を自動取得しました。"}catch(e){$("status").textContent=e.message||String(e)}}
function render(){$("messages").innerHTML=history.map(m=>`<div class="msg ${m.role}"><b>${m.role==="user"?"あなた":"キャラクター"}${m.mode==="do"?"（行動）":""}</b><br>${esc(m.content)}</div>`).join("");$("messages").scrollTop=$("messages").scrollHeight}
function system(){const name=$("character").value.trim()||"キャラクター",p=$("personality").value.trim(),style=$("style").value,len=$("length").value,subs=subcharacters();let cast=`メインキャラクター #0: 名前「${name}」${p?`、性格・設定「${p}」`:""}。`;if(subs.length){cast+=`\nサブキャラクター:\n`+subs.map(x=>`#${x.id}: 名前「${x.name}」${x.personality?`、性格・設定「${x.personality}」`:""}`).join("\n")+`\n同じ名前のキャラクターが複数いても統合せず、それぞれ別の個体として維持する。同一人物・コピー・分身という設定も許容し、各個体の発言と行動を混同しない。必要に応じて複数キャラクターを同じ場面に登場させる。複数人が話す場合は「名前(#番号): セリフ」の形式で誰の発言か分かるようにする。`};return `ロールプレイ会話をする。${cast}\n説明役ではなく登場人物本人として自然な日本語で返答する。${style==="daily"?"日常的で自然な口語を使う。":style==="iq80_crude"?"難語を避け、かなりくだけた口語を使う。":""}${len==="long"?"返答は長めにする。":len==="short"?"返答は短めにする。":""}${$("r18").checked?"利用者は18歳以上。成人同士の合意と安全を尊重した成人向け会話を許容する。未成年や非合意の性的内容は扱わない。":""}`}
async function send(mode,auto=false){const text=auto?"会話の流れに沿って、登場キャラクター側から自然に次の発言または行動を続けてください。":$("input").value.trim();if(!text)return;const s=await window.lexis.getSettings();if(!s.apiKey){$("status").textContent="OpenRouter APIキーを小説生成画面で保存してください。";return}if(!auto){history.push({role:"user",mode,content:text});$("input").value="";save();render()}$("status").textContent="生成中…";try{const msgs=[{role:"system",content:system()},...history.map(m=>({role:m.role,content:m.mode==="do"?`[行動] ${m.content}`:m.content}))];if(auto)msgs.push({role:"user",content:text});const r=await fetch("https://openrouter.ai/api/v1/chat/completions",{method:"POST",headers:{Authorization:"Bearer "+s.apiKey,"Content-Type":"application/json","X-Title":"Lexis AI Chat"},body:JSON.stringify({model:$("model").value||s.model||"openrouter/auto",messages:msgs,max_tokens:$("length").value==="long"?1800:$("length").value==="short"?300:900})}),d=await r.json();if(!r.ok)throw new Error(d?.error?.message||`API error ${r.status}`);const reply=String(d?.choices?.[0]?.message?.content||"").trim();if(!reply)throw new Error("AIから空の返信が返りました");history.push({role:"assistant",mode:"say",content:reply});save();render();$("status").textContent=""}catch(e){$("status").textContent=e.message||String(e)}}
$("say").onclick=()=>send("say");$("do").onclick=()=>send("do");$("auto").onclick=()=>send("say",true);$("augmentMain").onclick=augmentMain;$("augmentSubs").onclick=augmentSubs;$("clear").onclick=()=>{if(confirm("AIチャット履歴を消しますか？")){history=[];save();render()}};["character","personality","subcharacters","animeTitle"].forEach(id=>$(id).addEventListener("change",save));
(async()=>{const s=await window.lexis.getSettings();const models=await window.lexis.listModels({apiKey:s.apiKey}).catch(()=>[]);const ids=Array.isArray(models)?models.map(x=>typeof x==="string"?x:x.id).filter(Boolean):[];if(!ids.length)ids.push(s.model||"openrouter/auto");$("model").innerHTML=ids.map(x=>`<option>${esc(x)}</option>`).join("");if(s.model)$("model").value=s.model;load()})();