const $=id=>document.getElementById(id),KEY="lexis_consultation_threads_v1",RETRY_KEY="lexis_consultation_retry_count";let current=null;
function esc(s){return String(s||"").replace(/[&<>]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[c]))}
function load(){try{return JSON.parse(localStorage.getItem(KEY)||"[]")}catch{return[]}}
function save(x){localStorage.setItem(KEY,JSON.stringify(x))}
function retryCount(){const n=parseInt($("retryCount").value,10);return Number.isFinite(n)?Math.max(0,Math.min(100,n)):20}
function isCannedRefusal(s){const x=String(s||"").replace(/\s+/g," ");return[/申し訳ありませんが.*対応できません/,/ご要望にお応えすることはできません/,/露骨な性的行為.*(?:生成|描写).*(?:できません|対応できません)/,/その(?:ため|内容).*お手伝いできません/,/I(?:'m| am) sorry.*(?:can't|cannot).*assist/i,/I can(?:not|'t) help with that/i].some(r=>r.test(x))}
function imageUrls(message){const out=[];for(const x of(message?.images||[])){const u=x?.image_url?.url||x?.url||(typeof x==="string"?x:"");if(typeof u==="string"&&(u.startsWith("data:image/")||/^https?:\/\//i.test(u)))out.push(u)}return out}
function render(t){current=t||null;$("messages").innerHTML=current?(current.messages||[]).map(m=>{const imgs=(m.images||[]).map(u=>`<img src="${esc(u)}" style="display:block;max-width:100%;max-height:640px;margin-top:10px;border-radius:10px" loading="lazy">`).join("");return `<div class="msg ${m.role}"><b>${m.role==="user"?"あなた":"AI"}</b><br>${esc(m.content)}${imgs}</div>`}).join(""):"";$("messages").scrollTop=$("messages").scrollHeight}
function refresh(id){const ts=load();$("thread").innerHTML=ts.map(t=>`<option value="${t.id}">${esc(t.title||"新しい相談")}</option>`).join("");const x=id||current?.id||ts[0]?.id;if(x){$("thread").value=String(x);render(ts.find(t=>String(t.id)===String(x)))}else render(null)}
function create(){const t={id:Date.now(),title:"新しい相談",messages:[]};save([t,...load()]);refresh(t.id);return t}
async function requestWithRetry(url,options){const retries=retryCount();let last;for(let attempt=0;attempt<=retries;attempt++){try{const r=await fetch(url,options),raw=await r.text();let d;try{d=JSON.parse(raw)}catch{last=new Error("OpenRouterから不正なJSONが返りました");if(attempt<retries){$("status").textContent=`JSON不正のため再試行 ${attempt+1}/${retries}`;continue}throw last}if(!r.ok)throw new Error(d?.error?.message||"OpenRouter API error: "+r.status);const message=d?.choices?.[0]?.message||{},answer=typeof message.content==="string"?message.content.trim():"",images=imageUrls(message);if((!answer&&!images.length)||isCannedRefusal(answer)){last=new Error(!answer&&!images.length?"AIから空の返信が返りました":"AIから定型的な拒否応答が返りました");if(attempt<retries){$("status").textContent=`${!answer&&!images.length?"空の返信":"定型的な拒否応答"}のため再試行 ${attempt+1}/${retries}`;continue}throw last}return{d,answer,images}}catch(e){last=e;if((e.message||"").includes("不正なJSON")||(e.message||"").includes("空の返信")||(e.message||"").includes("定型的な拒否応答")){if(attempt<retries)continue}throw e}}throw last||new Error("AIから返信を取得できませんでした")}
$("thread").onchange=()=>render(load().find(t=>String(t.id)===$("thread").value));$("newThread").onclick=()=>create();$("retryCount").onchange=()=>localStorage.setItem(RETRY_KEY,String(retryCount()));
$("send").onclick=async()=>{const text=$("input").value.trim();if(!text)return;$("send").disabled=true;$("status").textContent="送信中…";try{const s=await window.lexis.getSettings();if(!s.apiKey)throw new Error("小説生成画面でOpenRouter APIキーを保存してください。");if(!current)current=create();let ts=load(),t=ts.find(x=>String(x.id)===String(current.id));t.messages.push({role:"user",content:text});if(t.title==="新しい相談")t.title=text.replace(/\s+/g," ").slice(0,30);save(ts);render(t);$("input").value="";const system=$("adult").checked?"あなたは日本語のAI相談員です。利用者は18歳以上の成人です。恋愛、性、性生活、性的嗜好など成人の性的な相談も必要以上に避けず、落ち着いて具体的に回答してください。画像を求められた場合は利用可能な画像生成ツールを使ってください。成人同士の合意、安全、プライバシーを尊重し、未成年を性的に扱う内容や非合意の性的行為を肯定・促進しないでください。":"あなたは日本語のAI相談員です。相談を整理し、共感的かつ具体的に回答してください。画像を求められた場合は利用可能な画像生成ツールを使ってください。医療・法律など高リスク分野では断定せず専門家への相談も案内してください。";const options={method:"POST",headers:{Authorization:"Bearer "+s.apiKey,"Content-Type":"application/json","X-Title":"Lexis AI Consultation"},body:JSON.stringify({model:$("model").value.trim()||s.model||"openrouter/auto",messages:[{role:"system",content:system},...t.messages],tools:[{type:"openrouter:image_generation"}],max_tokens:2048})};const {answer,images}=await requestWithRetry("https://openrouter.ai/api/v1/chat/completions",options);ts=load();t=ts.find(x=>String(x.id)===String(current.id));t.messages.push({role:"assistant",content:answer||"画像を生成しました。",images});save(ts);refresh(t.id);$("status").textContent=""}catch(e){$("status").textContent=e.message||String(e)}finally{$("send").disabled=false}};
(async()=>{const s=await window.lexis.getSettings();$("model").value=s.model||"openrouter/auto";$("adult").checked=!!s.r18;$("retryCount").value=localStorage.getItem(RETRY_KEY)||"20";refresh();if(!load().length)create()})();