import os
import math
import hashlib
import base64
import hmac
import secrets
import re
import time
import asyncio
import logging
import threading
from urllib.parse import urlencode, quote, parse_qs, urlparse, urljoin
import json
import html
import io
from datetime import date, datetime, timedelta, timezone
from functools import lru_cache, partial
from typing import Optional, List, Callable, Awaitable, Literal, Any

import jwt
import stripe
import httpx
import fastapi.routing as fastapi_routing
try:
    import redis  # type: ignore
except Exception:
    redis = None  # type: ignore
from fastapi import (
    APIRouter,
    FastAPI,
    Depends,
    HTTPException,
    Request,
    BackgroundTasks,
    Body,
    File,
    Form,
    status,
    Query,
    UploadFile,
)
from fastapi.encoders import jsonable_encoder as fastapi_jsonable_encoder
from fastapi.middleware.cors import CORSMiddleware
from fastapi.security import OAuth2PasswordBearer
from passlib.context import CryptContext
from pydantic import BaseModel, EmailStr, Field
from fastapi.responses import HTMLResponse, Response, RedirectResponse
from fastapi.staticfiles import StaticFiles
from sqlalchemy.orm import Session, aliased
from sqlalchemy import text, or_, func, case, bindparam
from sqlalchemy.orm import selectinload
from sqlalchemy import and_
from sqlalchemy.exc import IntegrityError

from .cache_helpers import (
    COMMENT_COUNT_AGG_VERSION,
    REDIS_PUBLIC_LIST_CACHE_TTL_SEC,
    REDIS_PUBLIC_USER_CACHE_TTL_SEC,
    REDIS_RANKING_CACHE_TTL_SEC,
    REDIS_USER_CACHE_TTL_SEC,
    _cache_key_user_by_name,
    _cache_key_user_profile,
    _normalize_optional_ai_model,
    _start_redis_metrics_flusher_if_enabled,
    build_public_cache_key,
    cache_user_payload,
    enqueue_episode_like_delta,
    enqueue_episode_view,
    enqueue_novel_like_delta,
    enqueue_novel_view,
    flush_redis_counters_once,
    get_redis_client,
    invalidate_public_list_caches,
    invalidate_user_cache,
    redis_delete,
    redis_delete_pattern,
    redis_json_get,
    redis_json_set,
)
from .database import get_db, SessionLocal
from .db_bootstrap import ensure_all_tables_exist, run_db_bootstrap
from .admin_auth_helpers import (
    _set_admin_cookie,
    create_admin_token,
    get_admin_username,
    require_admin,
    verify_admin_token,
)
from .external_service_helpers import (
    GOOGLE_CSE_API_KEY,
    GOOGLE_CSE_CX,
    GOOGLE_INDEXING_CARRYOVER_KEY,
    GOOGLE_INDEXING_CARRYOVER_TTL_SEC,
    GOOGLE_INDEXING_DAILY_SUBMIT_LIMIT,
    GOOGLE_SEARCH_CONSOLE_SITE_URL,
    _build_auto_fill_snippets,
    _is_preferred_cse_host,
    _split_character_fullname_terms,
    _split_character_terms,
    _split_search_terms,
    verify_recaptcha_token,
)
from .public_indexing_helpers import (
    _build_indexing_target_items,
    _calc_indexing_priority_score,
    _classify_indexing_page_type,
    _clear_indexing_carryover_urls,
    _dedupe_urls_keep_order,
    _enqueue_indexnow_urls,
    _filter_frontend_origin_urls,
    _get_indexing_carryover_payload,
    _get_indexing_carryover_urls,
    _indexing_importance_weight,
    _indexnow_host_from_request,
    _indexnow_key_location,
    _is_episode_indexable_for_search,
    _is_frontend_origin_url,
    _is_novel_indexable_for_search,
    _merge_indexing_urls_prioritize_carryover,
    _set_indexing_carryover_urls,
    _sitemap_index_entries_for_site,
    _sitemap_index_xml,
    _sitemap_merge_urls,
    _sitemap_part_urls_for_site,
    _sitemap_urlset_xml,
    build_public_page_url_items,
    build_public_page_url_items_for_site,
    build_public_page_urls,
    build_public_page_urls_for_site,
)
from .google_indexing_helpers import (
    _build_google_indexing_access_token,
    _build_google_search_console_access_token,
    _google_indexing_retry_delay_seconds,
    _inspect_google_indexed_status,
    _is_google_indexing_daily_quota_error,
    _load_google_indexing_credentials,
    _load_google_search_console_credentials,
    _publish_google_indexing_url,
    _should_retry_google_indexing_publish,
)
from .schemas_ai_chat import (
    AIChatAnimeTitleCandidatesResponse,
    AIChatAnimeTitleCandidatesRequest,
    AIChatAutoContinueRequest,
    AIChatCharacterAugmentResponse,
    AIChatCharacterAugmentSource,
    AIChatCharacterAugmentRequest,
    AIChatCharacterImageUploadResponse,
    AIChatCharacterResponse,
    AIChatCharacterCreateRequest,
    AIChatCharacterUpdateRequest,
    AIChatEngagementSummaryItem,
    AIChatEngagementSummaryResponse,
    AIChatImageGenerateRequest,
    AIChatImageGenerateResponse,
    AIChatImageItem,
    AIChatMessageDeleteResponse,
    AIChatMessageImageDeleteResponse,
    AIChatMessageImageUploadResponse,
    AIChatMessageImportItemRequest,
    AIChatMessageImportRequest,
    AIChatMessageImportResponse,
    AIChatMessageResponse,
    AIChatNextLineSuggestResponse,
    AIChatNextLineSuggestRequest,
    AIChatPromptPreviewResponse,
    AIChatPublishRequest,
    AIChatPublicCharacterDetailResponse,
    AIChatPublicCharacterListItem,
    AIChatRequest,
    AIChatResponse,
    AIChatUsageHistoryItemOut,
    SummaryCandidatesRequest,
    TagCandidatesRequest,
    TitleCandidateRequest,
    TitleCandidatesRequest,
)
from .schemas_api import (
    AIChatAddonCheckoutRequest,
    AINovelAddonCheckoutRequest,
    AIPublicChatViewHistoryItemOut,
    AdminUiI18nJobStartRequest,
    AdminUiI18nRetranslateRemainingRequest,
    AdminUiI18nSourceItem,
    AdminAIChatTokenConsumerDayOut,
    AdminAIChatTokenConsumerOut,
    AdminAIChatTokenConsumersTimelineOut,
    AdminContactMessageOut,
    AdminContactRequest,
    AdminEmailTestAllOut,
    AdminIndexingCarryoverOut,
    AdminIndexingSubmitItem,
    AdminIndexingSubmitOut,
    AdminIndexingSubmitRequest,
    AdminIndexingUrlItem,
    AdminIndexingUrlsOut,
    AdminIndexNowSubmitItem,
    AdminIndexNowSubmitOut,
    AdminIndexNowSubmitRequest,
    AdminLoginRequest,
    AdminSEOPageUpsertRequest,
    AdminStripePremiumSyncByEmailRequest,
    AdminStripePremiumSyncByEmailResponse,
    AdminUserDeleteOut,
    AdminUserListOut,
    AdminUserNovelOut,
    AdminUserOut,
    EpisodeAssistCandidatesOut,
    LoginVerify,
    MembershipCheckoutRequest,
    MobilePushRegisterPayload,
    MobilePushUnregisterPayload,
    NovelSummaryCandidatesOut,
    NovelViewHistoryItemOut,
    NovelViewHistoryListOut,
    PasswordResetConfirm,
    PasswordResetRequest,
    PayoutMarkRequest,
    PayoutProfileUpdateRequest,
    PublicContactRequest,
    PushDebugPayload,
    PushSubscriptionKeysPayload,
    PushSubscriptionPayload,
    PushUnsubscribePayload,
    RegisterEmailStartRequest,
    SupportCheckoutRequest,
    SupportPlanAuthorOut,
    SupportPlanCreate,
    SupportPlanOut,
    SupportPlanUpdate,
    TagCandidatesOut,
    TitleCandidateOut,
    TitleCandidatesOut,
    Token,
    UserCreate,
    UserLogin,
    ViewHistoryRecordRequest,
)
from .schemas_ai_novel_legacy import AIChatHistoryItem
from .ui_i18n_helpers import _json_dumps_safe, _json_loads_list, _parse_iso_datetime
from .i18n_runtime import (
    I18nTranslateRequest,
    _UI_I18N_JOB_LOCK,
    _UI_I18N_JOB_MAX_KEEP,
    _UI_I18N_JOB_ORDER,
    _UI_I18N_JOBS,
    _build_ui_i18n_resume_context,
    _collect_ui_i18n_untranslated_source_items,
    _create_ui_i18n_job_row,
    _load_ui_i18n_job_row,
    _normalize_ui_i18n_source_items,
    _recover_ui_i18n_jobs_on_startup,
    _run_ui_i18n_background_job,
    _set_ui_i18n_job,
    _start_ui_i18n_watchdog_if_enabled,
    _translate_ui_texts,
    _ui_i18n_job_snapshot,
    _ui_i18n_list_jobs,
    upsert_episode_translation,
    upsert_novel_translation,
)
from .translation_helpers import (
    _daily_translation_bot_loop as _daily_translation_bot_loop_impl,
    _background_upsert_episode_and_novel_translation as _background_upsert_episode_and_novel_translation_impl,
    _background_upsert_episode_translation as _background_upsert_episode_translation_impl,
    _background_upsert_novel_translation as _background_upsert_novel_translation_impl,
    _can_translate_episode as _can_translate_episode_impl,
    _can_translate_novel as _can_translate_novel_impl,
    _has_recent_multilingual_ready_notification as _has_recent_multilingual_ready_notification_impl,
    _is_episode_translation_complete as _is_episode_translation_complete_impl,
    _is_novel_translation_complete as _is_novel_translation_complete_impl,
    _normalize_tag_names as _normalize_tag_names_impl,
    _notify_multilingual_ready_for_episode as _notify_multilingual_ready_for_episode_impl,
    _notify_multilingual_ready_for_novel as _notify_multilingual_ready_for_novel_impl,
    _resolve_public_novel_card_translations as _resolve_public_novel_card_translations_impl,
    _run_daily_translation_bot_once as _run_daily_translation_bot_once_impl,
    _should_enqueue_feed_novel_translation as _should_enqueue_feed_novel_translation_impl,
    _start_daily_translation_bot_if_enabled as _start_daily_translation_bot_if_enabled_impl,
    _translation_author_is_premium as _translation_author_is_premium_impl,
)
from .public_novel_helpers import (
    _apply_public_novel_age_filter,
    _build_episode_comment_count_subquery,
    _build_novel_comment_count_subquery,
    _build_public_comment_count_map,
    _build_public_cover_map,
    _build_public_latest_episode_activity_map,
    _expand_public_search_aliases,
    _resolve_public_viewer_age,
)
from .episode_publish_helpers import (
    apply_episode_publish_mode,
    is_episode_draft,
    is_novel_draft,
    normalize_episode_publish_mode,
    normalize_episode_status,
    normalize_optional_datetime,
    publish_scheduled_episodes,
    resolve_episode_publish_mode,
)
from .oauth_helpers import (
    OAUTH1_COMPLETED_REDIRECTS,
    OAUTH1_REQUEST_TOKEN_TTL_SECONDS,
    _get_oauth_account as _get_oauth_account_impl,
    _get_or_create_user_from_oauth as _get_or_create_user_from_oauth_impl,
    _is_android_app_oauth_start as _is_android_app_oauth_start_impl,
    _mark_oauth_code_used as _mark_oauth_code_used_impl,
    _oauth_android_app_url as _oauth_android_app_url_impl,
    _oauth_app_bridge_response as _oauth_app_bridge_response_impl,
    _build_oauth_state as _build_oauth_state_impl,
    _build_pkce_pair as _build_pkce_pair_impl,
    _decode_oauth_state as _decode_oauth_state_impl,
    _generate_unique_username as _generate_unique_username_impl,
    _normalize_redirect_path as _normalize_redirect_path_impl,
    _oauth_frontend_url as _oauth_frontend_url_impl,
    _oauth1_base_params as _oauth1_base_params_impl,
    _oauth1_build_auth_header as _oauth1_build_auth_header_impl,
    _peek_oauth1_completed_redirect as _peek_oauth1_completed_redirect_impl,
    _pop_oauth1_request_token as _pop_oauth1_request_token_impl,
    _oauth_redirect_uri as _oauth_redirect_uri_impl,
    _oauth_result_url as _oauth_result_url_impl,
    _request_origin as _request_origin_impl,
    _store_oauth1_completed_redirect as _store_oauth1_completed_redirect_impl,
    _store_oauth1_request_token as _store_oauth1_request_token_impl,
)
from .startup_helpers import build_lifespan
from .stripe_helpers import (
    _create_checkout_session_with_customer_fallback as _create_checkout_session_with_customer_fallback_impl,
    _find_active_monthly_subscription_by_email as _find_active_monthly_subscription_by_email_impl,
    _monthly_stripe_premium_sync_loop as _monthly_stripe_premium_sync_loop_impl,
    _run_monthly_stripe_premium_sync_once as _run_monthly_stripe_premium_sync_once_impl,
    _start_monthly_stripe_premium_sync_if_enabled as _start_monthly_stripe_premium_sync_if_enabled_impl,
    _stripe_checkout_customer_kwargs as _stripe_checkout_customer_kwargs_impl,
    _stripe_obj_get as _stripe_obj_get_impl,
    _stripe_subscription_is_active as _stripe_subscription_is_active_impl,
    _stripe_subscription_is_monthly as _stripe_subscription_is_monthly_impl,
    cancel_stripe_subscription_for_admin_delete as cancel_stripe_subscription_for_admin_delete_impl,
    premium_plan_usage_multiplier_for_user as premium_plan_usage_multiplier_for_user_impl,
    revalidate_premium_on_login as revalidate_premium_on_login_impl,
    verify_premium_with_stripe as verify_premium_with_stripe_impl,
)
from .ai_chat_prompt_helpers import (
    _build_ai_chat_branching_instruction as _build_ai_chat_branching_instruction_impl,
    _build_ai_chat_content_safety_rules as _build_ai_chat_content_safety_rules_impl,
    _build_ai_chat_history_text as _build_ai_chat_history_text_impl,
    _build_ai_chat_next_line_suggest_prompt as _build_ai_chat_next_line_suggest_prompt_impl,
    _build_ai_chat_prompt as _build_ai_chat_prompt_impl,
    _build_ai_chat_style_guide as _build_ai_chat_style_guide_impl,
    _build_ai_chat_system_instructions as _build_ai_chat_system_instructions_impl,
    _build_ai_chat_variation_instruction as _build_ai_chat_variation_instruction_impl,
    _build_auto_dialogue_prompt as _build_auto_dialogue_prompt_impl,
    _build_language_style_rules as _build_language_style_rules_impl,
    _build_multi_character_relationship_rules as _build_multi_character_relationship_rules_impl,
    _build_relationship_tone_rules as _build_relationship_tone_rules_impl,
    _normalize_chat_text_for_match as _normalize_chat_text_for_match_impl,
    _normalize_language_style as _normalize_language_style_impl,
)
from .ai_chat_scoring_helpers import (
    _build_ai_chat_engagement_learning_instruction as _build_ai_chat_engagement_learning_instruction_impl,
    _build_ai_chat_profile_key as _build_ai_chat_profile_key_impl,
    _build_ai_chat_recommendation_map as _build_ai_chat_recommendation_map_impl,
    _build_public_profile_recommendation_map as _build_public_profile_recommendation_map_impl,
    _calc_user_personalization_weight as _calc_user_personalization_weight_impl,
    _clip01 as _clip01_impl,
    _estimate_ai_reply_scores as _estimate_ai_reply_scores_impl,
    _estimate_user_followup_signal_scores as _estimate_user_followup_signal_scores_impl,
    _extract_personality_keywords as _extract_personality_keywords_impl,
    _normalized_keyword_score as _normalized_keyword_score_impl,
    _record_ai_chat_followup_feedback as _record_ai_chat_followup_feedback_impl,
    _score_ai_chat_followup_latency as _score_ai_chat_followup_latency_impl,
    _update_profile_learning_stats as _update_profile_learning_stats_impl,
)
from .ai_chat_runtime_helpers import (
    _ai_chat_provider_candidates as _ai_chat_provider_candidates_impl,
    _build_ai_chat_history_lines as _build_ai_chat_history_lines_impl,
    _build_data_url_from_local_image as _build_data_url_from_local_image_impl,
    _call_ai_chat_json_with_fallback as _call_ai_chat_json_with_fallback_impl,
    _collect_ai_chat_backfill_turns as _collect_ai_chat_backfill_turns_impl,
    _default_ai_chat_deepseek_model as _default_ai_chat_deepseek_model_impl,
    _default_ai_chat_openrouter_model as _default_ai_chat_openrouter_model_impl,
    _describe_uploaded_chat_images as _describe_uploaded_chat_images_impl,
    _extract_ai_chat_images_from_generate_data as _extract_ai_chat_images_from_generate_data_impl,
    _extract_background_place_prompt as _extract_background_place_prompt_impl,
    _extract_error_detail_from_response as _extract_error_detail_from_response_impl,
    _extract_image_field_from_payload as _extract_image_field_from_payload_impl,
    _extract_openai_responses_output_text as _extract_openai_responses_output_text_impl,
    _extract_session_token_from_payload as _extract_session_token_from_payload_impl,
    _fallback_next_line_suggestions as _fallback_next_line_suggestions_impl,
    _local_static_path_from_url as _local_static_path_from_url_impl,
    _long_reply_min_chars as _long_reply_min_chars_impl,
    _looks_like_fictional_character_name as _looks_like_fictional_character_name_impl,
    _normalize_ai_chat_image_url as _normalize_ai_chat_image_url_impl,
    _normalize_ai_chat_model_alias as _normalize_ai_chat_model_alias_impl,
    _normalize_next_line_suggestion as _normalize_next_line_suggestion_impl,
    _parse_ai_chat_image_message as _parse_ai_chat_image_message_impl,
    _read_secret_from_env_or_file as _read_secret_from_env_or_file_impl,
    _regenerate_auto_dialogue_if_needed as _regenerate_auto_dialogue_if_needed_impl,
    _regenerate_long_reply_if_needed as _regenerate_long_reply_if_needed_impl,
    _resolve_ai_chat_candidate_model as _resolve_ai_chat_candidate_model_impl,
    _resolve_ai_chat_provider as _resolve_ai_chat_provider_impl,
    _resolve_image_to_data_url as _resolve_image_to_data_url_impl,
    _score_ai_chat_image_quality as _score_ai_chat_image_quality_impl,
    _serialize_ai_chat_image_message as _serialize_ai_chat_image_message_impl,
)
from .ai_access_helpers import (
    _ai_chat_allowed_tokens as _ai_chat_allowed_tokens_impl,
    _can_edit_ai_chat_character as _can_edit_ai_chat_character_impl,
    _compute_ai_chat_name_duplicate_index as _compute_ai_chat_name_duplicate_index_impl,
    _current_ai_chat_month_key_utc as _current_ai_chat_month_key_utc_impl,
    _ensure_ai_chat_access as _ensure_ai_chat_access_impl,
    _ensure_ai_chat_guest_access as _ensure_ai_chat_guest_access_impl,
    _find_accessible_ai_chat_character as _find_accessible_ai_chat_character_impl,
    _find_editable_ai_chat_character as _find_editable_ai_chat_character_impl,
    _is_ai_chat_demo_bypass_user as _is_ai_chat_demo_bypass_user_impl,
    _is_ai_chat_demo_bypass_username as _is_ai_chat_demo_bypass_username_impl,
    _record_ai_chat_tokens as _record_ai_chat_tokens_impl,
    _sync_user_ai_chat_monthly_usage as _sync_user_ai_chat_monthly_usage_impl,
    check_ai_quota as check_ai_quota_impl,
    get_ai_chat_guest_usage as get_ai_chat_guest_usage_impl,
    get_guest_ai_usage as get_guest_ai_usage_impl,
    get_optional_current_user as get_optional_current_user_impl,
    get_optional_current_user_soft as get_optional_current_user_soft_impl,
    get_or_set_ai_guest_id as get_or_set_ai_guest_id_impl,
    require_guest_ai_quota as require_guest_ai_quota_impl,
    save_ai_log as save_ai_log_impl,
    save_ai_novel_request_log as save_ai_novel_request_log_impl,
)
from .ai_job_helpers import (
    _ai_novel_daily_max_for_user as _ai_novel_daily_max_for_user_impl,
    _ai_novel_paid_remaining as _ai_novel_paid_remaining_impl,
    _ai_novel_remaining_for_user as _ai_novel_remaining_for_user_impl,
    _build_chunked_job_response as _build_chunked_job_response_impl,
    _build_chunked_novel_prompt as _build_chunked_novel_prompt_impl,
    _call_ai_with_retry as _call_ai_with_retry_impl,
    _call_ai_with_retry_prompt as _call_ai_with_retry_prompt_impl,
    _count_ai_jobs_today as _count_ai_jobs_today_impl,
    _count_ai_usage_today as _count_ai_usage_today_impl,
    _is_ai_job_expired as _is_ai_job_expired_impl,
    _is_empty_ai_response_error as _is_empty_ai_response_error_impl,
    _kill_expired_ai_jobs as _kill_expired_ai_jobs_impl,
    _normalize_chunked_generation_payload as _normalize_chunked_generation_payload_impl,
    _reserve_ai_novel_generation_slot as _reserve_ai_novel_generation_slot_impl,
    _run_ai_job as _run_ai_job_impl,
    _serialize_ai_response as _serialize_ai_response_impl,
    _should_retry_ai_error as _should_retry_ai_error_impl,
)
from .ai_source_helpers import (
    _collect_novel_feature_docs as _collect_novel_feature_docs_impl,
    _collect_public_chat_preference_text as _collect_public_chat_preference_text_impl,
    _collect_user_preference_text_for_novels as _collect_user_preference_text_for_novels_impl,
)
from .content_helpers import (
    apply_novel_daily_metric as apply_novel_daily_metric_impl,
    deserialize_meta_tags as deserialize_meta_tags_impl,
    deserialize_tag_names as deserialize_tag_names_impl,
    get_novel_char_counts as get_novel_char_counts_impl,
    normalize_illust_tag as normalize_illust_tag_impl,
    normalize_language as normalize_language_impl,
    normalize_meta_tags as normalize_meta_tags_impl,
    normalize_translated_tags as normalize_translated_tags_impl,
    serialize_meta_tags as serialize_meta_tags_impl,
    serialize_tag_names as serialize_tag_names_impl,
    translation_target_languages as translation_target_languages_impl,
)
from .ai_text_helpers import (
    build_ai_novel_request_with_context as build_ai_novel_request_with_context_impl,
    compact_text as compact_text_impl,
    semantic_score_from_distance as semantic_score_from_distance_impl,
)
from .payout_reading_helpers import (
    apply_author_balance_delta as apply_author_balance_delta_impl,
    calc_author_share as calc_author_share_impl,
    calc_platform_fee as calc_platform_fee_impl,
    get_episode_number as get_episode_number_impl,
    get_or_create_author_balance as get_or_create_author_balance_impl,
    get_or_create_payout_profile as get_or_create_payout_profile_impl,
    is_free_reading_time as is_free_reading_time_impl,
    is_jp_holiday as is_jp_holiday_impl,
    parse_payout_period as parse_payout_period_impl,
    set_episode_number as set_episode_number_impl,
    truncate_for_free as truncate_for_free_impl,
)
from .site_helpers import (
    get_episode_in_site_or_404 as get_episode_in_site_or_404_impl,
    get_novel_in_site_or_404 as get_novel_in_site_or_404_impl,
    get_or_create_tags as get_or_create_tags_impl,
    normalize_site_key as normalize_site_key_impl,
    resolve_site_key as resolve_site_key_impl,
    truncate_text as truncate_text_impl,
)
from .user_access_helpers import (
    assert_premium_user as assert_premium_user_impl,
    calc_age as calc_age_impl,
    create_access_token as create_access_token_impl,
    get_follow_counts as get_follow_counts_impl,
    get_user_by_username as get_user_by_username_impl,
    hash_password as hash_password_impl,
    hash_register_email_code as hash_register_email_code_impl,
    hash_reset_token as hash_reset_token_impl,
    is_effective_premium_user as is_effective_premium_user_impl,
    is_following_user as is_following_user_impl,
    is_force_premium_username as is_force_premium_username_impl,
    normalize_dm_pair as normalize_dm_pair_impl,
    normalize_email as normalize_email_impl,
    read_token_user_id as read_token_user_id_impl,
    record_user_view_history as record_user_view_history_impl,
    require_current_user as require_current_user_impl,
    require_premium_user as require_premium_user_impl,
    verify_password as verify_password_impl,
)
from .legacy_helpers import (
    _extract_retry_max_from_request_json as _extract_retry_max_from_request_json_impl,
    _format_ai_log_model as _format_ai_log_model_impl,
    get_episode_tag_names as get_episode_tag_names_impl,
    get_novel_tag_names as get_novel_tag_names_impl,
    normalize_speech_gender as normalize_speech_gender_impl,
)
from .notification_helpers import (
    FIREBASE_SERVICE_ACCOUNT_FILE,
    FIREBASE_SERVICE_ACCOUNT_JSON,
    SMTP_FROM,
    SMTP_HOST,
    SMTP_PASS,
    SMTP_PORT,
    SMTP_USER,
    WEBPUSH_VAPID_PUBLIC_KEY,
    can_user_access_novel_age_limit,
    create_notification,
    ensure_fcm_initialized,
    get_user_favorite_tag_weights,
    is_fcm_configured,
    is_webpush_configured,
    notify_favorited_users_episode_published,
    notify_followers_author_new_episode,
    notify_followers_author_new_novel,
    notify_recommended_users_new_novel,
    notify_tag_followers_new_novel,
    send_admin_contact_email,
    send_fcm_push_to_user,
    send_notification_email,
    send_notification_email_if_enabled,
    send_notification_email_if_enabled_with_user,
    send_public_contact_email,
    send_test_email_and_detect_invalid_address,
    send_web_push_to_user,
    _background_notify_episode_published as _background_notify_episode_published_impl,
    _notify_ai_job_user as _notify_ai_job_user_impl,
    _is_unknown_email_address_error,
    _load_firebase_credential_dict,
    _notification_target_url,
)
from .author_dashboard_helpers import _collect_author_dashboard_rows, _table_has_column
from .auth_mail_helpers import (
    send_2fa_email,
    send_password_reset_email,
    send_register_email_verification_code,
)
from .public_chat_helpers import (
    _contains_public_chat_r18_hint,
    _is_public_chat_r18,
    _trim_public_character_intro,
)
from .time_utils import (
    display_payload_in_jst as display_payload_in_jst_impl,
    display_payload_in_utc as display_payload_in_utc_impl,
    to_jst_isoformat as to_jst_isoformat_impl,
    to_utc_isoformat as to_utc_isoformat_impl,
    utcnow as utcnow_impl,
)
from .runtime_export_builders import (
    build_ai_runtime_exports,
    build_auth_runtime_exports,
    build_core_runtime_exports,
    build_shared_runtime_exports,
    build_translation_runtime_exports,
    install_utc_json_encoder,
)
from .runtime_config import *  # noqa: F401,F403
from .rate_limit_helpers import (
    _admin_login_remote_ip,
    _clear_admin_login_rate_limit_state,
    _enforce_admin_login_rate_limit,
    _enforce_ai_chat_rate_limit,
    _enforce_login_start_abuse_guards,
    _enforce_login_start_send_cooldown,
    _enforce_public_contact_abuse_guards,
    _enforce_register_email_start_abuse_guards,
    _mark_login_start_send,
    _public_contact_remote_ip,
    _record_admin_login_failure,
    _record_login_start_failure,
    _record_public_contact_submission,
    _record_register_email_start_attempt,
    _clear_login_start_failure,
)
from . import models, schemas
from .routers.feed import list_trending_feed


from .ai_novel import (
    AINovelJobCreateResponse,
    AINovelRequest,
    AINovelResponse,
    assert_openrouter_model_allowed_for_pricing,
    build_ai_prompt,
    call_ai_json,
    call_openai_catch_copy_candidates,
    call_openai_novel_api,
    call_openrouter_novel_api,
    call_deepseek_novel_api,
    call_local_novel_api,
    list_ai_novel_models,
    call_openai_summary_candidates,
    call_openai_tag_candidates,
    call_openai_title_candidate,
    call_openai_title_candidates,
    provider_from_model,
    provider_from_request,
)
from .ai.chat_engine import (
    build_layered_context_block,
    build_summary_text,
    format_long_term_memories,
)
from .ai.memory_service import (
    resolve_scope as resolve_memory_scope,
    retrieve_memories,
)
from .ai.weaviate_client import ensure_schema as ensure_weaviate_schema
from .ai.weaviate_features import (
    bm25_search_feature_docs,
    ensure_feature_schema as ensure_weaviate_feature_schema,
    scan_feature_docs,
    semantic_search_feature_docs,
    upsert_feature_docs,
)
from .features import include_feature_routers
from .features.public_feature_service import list_recommended_public_novels_service

try:
    from PIL import Image, ImageOps  # type: ignore

    PIL_AVAILABLE = True
except Exception:
    PIL_AVAILABLE = False

run_db_bootstrap()
globals().update(
    build_shared_runtime_exports(
        utcnow_impl=utcnow_impl,
        to_jst_isoformat_impl=to_jst_isoformat_impl,
        to_utc_isoformat_impl=to_utc_isoformat_impl,
        display_payload_in_jst_impl=display_payload_in_jst_impl,
        display_payload_in_utc_impl=display_payload_in_utc_impl,
        get_novel_char_counts_impl=get_novel_char_counts_impl,
        apply_novel_daily_metric_impl=apply_novel_daily_metric_impl,
        normalize_illust_tag_impl=normalize_illust_tag_impl,
        normalize_meta_tags_impl=normalize_meta_tags_impl,
        serialize_meta_tags_impl=serialize_meta_tags_impl,
        deserialize_meta_tags_impl=deserialize_meta_tags_impl,
        normalize_language_impl=normalize_language_impl,
        serialize_tag_names_impl=serialize_tag_names_impl,
        deserialize_tag_names_impl=deserialize_tag_names_impl,
        normalize_translated_tags_impl=normalize_translated_tags_impl,
    )
)
install_utc_json_encoder(
    fastapi_routing_module=fastapi_routing,
    fastapi_jsonable_encoder=fastapi_jsonable_encoder,
    datetime_cls=datetime,
    to_utc_isoformat=to_utc_isoformat,
)

# =========================================
# FastAPI
# =========================================
app = FastAPI(
    docs_url="/api/docs",
    redoc_url="/api/redoc",
    openapi_url="/api/openapi.json",
    lifespan=build_lifespan(
        ensure_all_tables_exist=ensure_all_tables_exist,
        episode_image_dir=str(EPISODE_IMAGE_DIR),
        ai_chat_character_image_dir=str(AI_CHAT_CHARACTER_IMAGE_DIR),
        ai_chat_message_image_dir=str(AI_CHAT_MESSAGE_IMAGE_DIR),
        blog_image_dir=str(BLOG_IMAGE_DIR),
        cover_upload_dir=str(COVER_UPLOAD_DIR),
        get_redis_client=get_redis_client,
        start_redis_metrics_flusher_if_enabled=_start_redis_metrics_flusher_if_enabled,
        start_daily_translation_bot_if_enabled=lambda: _start_daily_translation_bot_if_enabled(),
        start_monthly_stripe_premium_sync_if_enabled=lambda: _start_monthly_stripe_premium_sync_if_enabled(),
        start_ui_i18n_watchdog_if_enabled=_start_ui_i18n_watchdog_if_enabled,
        recover_ui_i18n_jobs_on_startup=_recover_ui_i18n_jobs_on_startup,
        ai_chat_memory_enabled=AI_CHAT_MEMORY_ENABLED,
        ensure_weaviate_schema=ensure_weaviate_schema,
        ai_weaviate_features_enabled=AI_WEAVIATE_FEATURES_ENABLED,
        ensure_weaviate_feature_schema=ensure_weaviate_feature_schema,
        logger=logging.getLogger("uvicorn.error"),
    ),
)

app.mount("/static", StaticFiles(directory=str(STATIC_DIR)), name="static")
app.mount("/uploads", StaticFiles(directory=str(UPLOADS_DIR), check_dir=False), name="uploads")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # 本番は必要に応じて絞る
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

include_feature_routers(app)
stripe.api_key = STRIPE_SECRET_KEY
logger = logging.getLogger("uvicorn.error")
globals().update(
    build_core_runtime_exports(
        compact_text_impl=compact_text_impl,
        semantic_score_from_distance_impl=semantic_score_from_distance_impl,
        build_ai_novel_request_with_context_impl=build_ai_novel_request_with_context_impl,
        collect_novel_feature_docs_impl=_collect_novel_feature_docs_impl,
        collect_user_preference_text_for_novels_impl=_collect_user_preference_text_for_novels_impl,
        collect_public_chat_preference_text_impl=_collect_public_chat_preference_text_impl,
        get_user_favorite_tag_weights=get_user_favorite_tag_weights,
        stripe_checkout_customer_kwargs_impl=_stripe_checkout_customer_kwargs_impl,
        create_checkout_session_with_customer_fallback_impl=_create_checkout_session_with_customer_fallback_impl,
        stripe_module=stripe,
        normalize_site_key_impl=normalize_site_key_impl,
        resolve_site_key_impl=resolve_site_key_impl,
        get_novel_in_site_or_404_impl=get_novel_in_site_or_404_impl,
        get_episode_in_site_or_404_impl=get_episode_in_site_or_404_impl,
        get_or_create_tags_impl=get_or_create_tags_impl,
        normalize_tag_names_impl=_normalize_tag_names_impl,
        truncate_text_impl=truncate_text_impl,
        ai_weaviate_features_topk=AI_WEAVIATE_FEATURES_TOPK,
        ai_novel_request_cls=AINovelRequest,
        site_key_default=SITE_KEY_DEFAULT,
        site_key_allowed=SITE_KEY_ALLOWED,
        site_host_map=SITE_HOST_MAP,
        models=models,
        http_exception_cls=HTTPException,
        integrity_error_cls=IntegrityError,
    )
)

globals().update(
    build_translation_runtime_exports(
        translation_target_languages_impl=translation_target_languages_impl,
        novel_translation_original_only=NOVEL_TRANSLATION_ORIGINAL_ONLY,
        novel_translation_ja_en_only=NOVEL_TRANSLATION_JA_EN_ONLY,
        novel_translation_all_languages=NOVEL_TRANSLATION_ALL_LANGUAGES,
        has_recent_multilingual_ready_notification_impl=_has_recent_multilingual_ready_notification_impl,
        is_novel_translation_complete_impl=_is_novel_translation_complete_impl,
        is_episode_translation_complete_impl=_is_episode_translation_complete_impl,
        notify_multilingual_ready_for_novel_impl=_notify_multilingual_ready_for_novel_impl,
        notify_multilingual_ready_for_episode_impl=_notify_multilingual_ready_for_episode_impl,
        run_daily_translation_bot_once_impl=_run_daily_translation_bot_once_impl,
        daily_translation_bot_loop_impl=_daily_translation_bot_loop_impl,
        start_daily_translation_bot_if_enabled_impl=_start_daily_translation_bot_if_enabled_impl,
        run_monthly_stripe_premium_sync_once_impl=_run_monthly_stripe_premium_sync_once_impl,
        monthly_stripe_premium_sync_loop_impl=_monthly_stripe_premium_sync_loop_impl,
        start_monthly_stripe_premium_sync_if_enabled_impl=_start_monthly_stripe_premium_sync_if_enabled_impl,
        background_upsert_episode_translation_impl=_background_upsert_episode_translation_impl,
        background_upsert_episode_and_novel_translation_impl=_background_upsert_episode_and_novel_translation_impl,
        background_upsert_novel_translation_impl=_background_upsert_novel_translation_impl,
        should_enqueue_feed_novel_translation_impl=_should_enqueue_feed_novel_translation_impl,
        resolve_public_novel_card_translations_impl=_resolve_public_novel_card_translations_impl,
        background_notify_episode_published_impl=_background_notify_episode_published_impl,
        session_local=SessionLocal,
        models=models,
        logger=logger,
        deserialize_tag_names=deserialize_tag_names,
        get_episode_tag_names_impl=get_episode_tag_names_impl,
        create_notification=create_notification,
        daily_translation_bot_only_public=DAILY_TRANSLATION_BOT_ONLY_PUBLIC,
        daily_translation_bot_site_key=DAILY_TRANSLATION_BOT_SITE_KEY,
        daily_translation_bot_max_novels=DAILY_TRANSLATION_BOT_MAX_NOVELS,
        daily_translation_bot_max_episodes=DAILY_TRANSLATION_BOT_MAX_EPISODES,
        can_translate_novel=lambda db, *, novel: _can_translate_novel(db, novel=novel),
        can_translate_episode=lambda db, *, episode: _can_translate_episode(db, episode=episode),
        normalize_language=normalize_language,
        get_novel_tag_names_impl=get_novel_tag_names_impl,
        upsert_novel_translation=upsert_novel_translation,
        upsert_episode_translation=upsert_episode_translation,
        is_episode_draft=is_episode_draft,
        daily_translation_bot_interval_seconds=DAILY_TRANSLATION_BOT_INTERVAL_SECONDS,
        time_module=time,
        threading_module=threading,
        daily_translation_bot_enabled=DAILY_TRANSLATION_BOT_ENABLED,
        stripe_secret_key=STRIPE_SECRET_KEY,
        find_active_monthly_subscription_by_email=lambda email: _find_active_monthly_subscription_by_email(email),
        is_ai_chat_demo_bypass_user=lambda user: _is_ai_chat_demo_bypass_user(user),
        is_force_premium_username=lambda username: _is_force_premium_username(username),
        func=func,
        monthly_stripe_premium_sync_day=MONTHLY_STRIPE_PREMIUM_SYNC_DAY,
        monthly_stripe_premium_sync_hour_utc=MONTHLY_STRIPE_PREMIUM_SYNC_HOUR_UTC,
        monthly_stripe_premium_sync_interval_seconds=MONTHLY_STRIPE_PREMIUM_SYNC_INTERVAL_SECONDS,
        datetime_module=datetime,
        monthly_stripe_premium_sync_enabled=MONTHLY_STRIPE_PREMIUM_SYNC_ENABLED,
    )
)

globals().update(
    build_auth_runtime_exports(
        module_globals=globals(),
        get_db=get_db,
        jwt_module=jwt,
        stripe_module=stripe,
        html_response_cls=HTMLResponse,
        http_exception_cls=HTTPException,
        status_module=status,
        secret_key=SECRET_KEY,
        algorithm=ALGORITHM,
        access_token_expire_minutes=ACCESS_TOKEN_EXPIRE_MINUTES,
        password_reset_expire_minutes=PASSWORD_RESET_EXPIRE_MINUTES,
        register_email_verify_expire_minutes=REGISTER_EMAIL_VERIFY_EXPIRE_MINUTES,
        oauth_state_expire_minutes=OAUTH_STATE_EXPIRE_MINUTES,
        stripe_secret_key=STRIPE_SECRET_KEY,
        stripe_price_id_3000=STRIPE_PRICE_ID_3000,
        stripe_price_id_5000=STRIPE_PRICE_ID_5000,
        platform_fee_rate=PLATFORM_FEE_RATE,
        force_all_premium=FORCE_ALL_PREMIUM,
        force_premium_usernames=FORCE_PREMIUM_USERNAMES,
        premium_revalidate_days=PREMIUM_REVALIDATE_DAYS,
        x_oauth_consumer_key=X_OAUTH_CONSUMER_KEY,
        x_oauth_consumer_secret=X_OAUTH_CONSUMER_SECRET,
        backend_origin=BACKEND_ORIGIN,
        frontend_origin=FRONTEND_ORIGIN,
        ai_chat_demo_bypass_username=AI_CHAT_DEMO_BYPASS_USERNAME,
        ai_chat_premium_included_blocks=AI_CHAT_PREMIUM_INCLUDED_BLOCKS,
        ai_chat_free_tokens=AI_CHAT_FREE_TOKENS,
        ai_chat_guest_tokens=AI_CHAT_GUEST_TOKENS,
        ai_chat_block_tokens=AI_CHAT_BLOCK_TOKENS,
        ai_chat_block_price_yen=AI_CHAT_BLOCK_PRICE_YEN,
        ai_novel_addon_unit_generations=AI_NOVEL_ADDON_UNIT_GENERATIONS,
        ai_novel_addon_price_yen=AI_NOVEL_ADDON_PRICE_YEN,
        ai_job_timeout_minutes=AI_JOB_TIMEOUT_MINUTES,
        os_module=os,
        secrets_module=secrets,
        models=models,
        func=func,
        redis_json_get=redis_json_get,
        cache_key_user_by_name=_cache_key_user_by_name,
        cache_user_payload=cache_user_payload,
        invalidate_user_cache=invalidate_user_cache,
        normalize_site_key=normalize_site_key,
        verify_password_impl=verify_password_impl,
        hash_password_impl=hash_password_impl,
        hash_reset_token_impl=hash_reset_token_impl,
        normalize_email_impl=normalize_email_impl,
        hash_register_email_code_impl=hash_register_email_code_impl,
        create_access_token_impl=create_access_token_impl,
        build_pkce_pair_impl=_build_pkce_pair_impl,
        build_oauth_state_impl=_build_oauth_state_impl,
        decode_oauth_state_impl=_decode_oauth_state_impl,
        normalize_redirect_path_impl=_normalize_redirect_path_impl,
        generate_unique_username_impl=_generate_unique_username_impl,
        mark_oauth_code_used_impl=_mark_oauth_code_used_impl,
        store_oauth1_request_token_impl=_store_oauth1_request_token_impl,
        store_oauth1_completed_redirect_impl=_store_oauth1_completed_redirect_impl,
        peek_oauth1_completed_redirect_impl=_peek_oauth1_completed_redirect_impl,
        pop_oauth1_request_token_impl=_pop_oauth1_request_token_impl,
        oauth1_build_auth_header_impl=_oauth1_build_auth_header_impl,
        oauth1_base_params_impl=_oauth1_base_params_impl,
        stripe_obj_get_impl=_stripe_obj_get_impl,
        stripe_subscription_is_active_impl=_stripe_subscription_is_active_impl,
        stripe_subscription_is_monthly_impl=_stripe_subscription_is_monthly_impl,
        find_active_monthly_subscription_by_email_impl=_find_active_monthly_subscription_by_email_impl,
        verify_premium_with_stripe_impl=verify_premium_with_stripe_impl,
        cancel_stripe_subscription_for_admin_delete_impl=cancel_stripe_subscription_for_admin_delete_impl,
        premium_plan_usage_multiplier_for_user_impl=premium_plan_usage_multiplier_for_user_impl,
        translation_author_is_premium_impl=_translation_author_is_premium_impl,
        can_translate_novel_impl=_can_translate_novel_impl,
        can_translate_episode_impl=_can_translate_episode_impl,
        revalidate_premium_on_login_impl=revalidate_premium_on_login_impl,
        calc_platform_fee_impl=calc_platform_fee_impl,
        calc_author_share_impl=calc_author_share_impl,
        get_or_create_author_balance_impl=get_or_create_author_balance_impl,
        apply_author_balance_delta_impl=apply_author_balance_delta_impl,
        get_or_create_payout_profile_impl=get_or_create_payout_profile_impl,
        parse_payout_period_impl=parse_payout_period_impl,
        truncate_for_free_impl=truncate_for_free_impl,
        is_jp_holiday_impl=is_jp_holiday_impl,
        is_free_reading_time_impl=is_free_reading_time_impl,
        get_episode_number_impl=get_episode_number_impl,
        set_episode_number_impl=set_episode_number_impl,
        get_user_by_username_impl=get_user_by_username_impl,
        get_follow_counts_impl=get_follow_counts_impl,
        is_following_user_impl=is_following_user_impl,
        normalize_dm_pair_impl=normalize_dm_pair_impl,
        require_current_user_impl=require_current_user_impl,
        read_token_user_id_impl=read_token_user_id_impl,
        record_user_view_history_impl=record_user_view_history_impl,
        calc_age_impl=calc_age_impl,
        require_premium_user_impl=require_premium_user_impl,
        is_force_premium_username_impl=is_force_premium_username_impl,
        is_effective_premium_user_impl=is_effective_premium_user_impl,
        assert_premium_user_impl=assert_premium_user_impl,
        is_ai_chat_demo_bypass_user_impl=_is_ai_chat_demo_bypass_user_impl,
        is_ai_chat_demo_bypass_username_impl=_is_ai_chat_demo_bypass_username_impl,
        can_edit_ai_chat_character_impl=_can_edit_ai_chat_character_impl,
        find_editable_ai_chat_character_impl=_find_editable_ai_chat_character_impl,
        find_accessible_ai_chat_character_impl=_find_accessible_ai_chat_character_impl,
        compute_ai_chat_name_duplicate_index_impl=_compute_ai_chat_name_duplicate_index_impl,
        ai_chat_allowed_tokens_impl=_ai_chat_allowed_tokens_impl,
        current_ai_chat_month_key_utc_impl=_current_ai_chat_month_key_utc_impl,
        sync_user_ai_chat_monthly_usage_impl=_sync_user_ai_chat_monthly_usage_impl,
        ensure_ai_chat_access_impl=_ensure_ai_chat_access_impl,
        ensure_ai_chat_guest_access_impl=_ensure_ai_chat_guest_access_impl,
        record_ai_chat_tokens_impl=_record_ai_chat_tokens_impl,
        get_optional_current_user_impl=get_optional_current_user_impl,
        get_optional_current_user_soft_impl=get_optional_current_user_soft_impl,
        get_or_set_ai_guest_id_impl=get_or_set_ai_guest_id_impl,
        get_guest_ai_usage_impl=get_guest_ai_usage_impl,
        get_ai_chat_guest_usage_impl=get_ai_chat_guest_usage_impl,
        require_guest_ai_quota_impl=require_guest_ai_quota_impl,
        check_ai_quota_impl=check_ai_quota_impl,
        save_ai_log_impl=save_ai_log_impl,
        save_ai_novel_request_log_impl=save_ai_novel_request_log_impl,
        request_origin_impl=_request_origin_impl,
        oauth_redirect_uri_impl=_oauth_redirect_uri_impl,
        oauth_frontend_url_impl=_oauth_frontend_url_impl,
        oauth_android_app_url_impl=_oauth_android_app_url_impl,
        oauth_result_url_impl=_oauth_result_url_impl,
        oauth_app_bridge_response_impl=_oauth_app_bridge_response_impl,
        is_android_app_oauth_start_impl=_is_android_app_oauth_start_impl,
        get_oauth_account_impl=_get_oauth_account_impl,
        get_or_create_user_from_oauth_impl=_get_or_create_user_from_oauth_impl,
    )
)

globals().update(
    build_ai_runtime_exports(
        re_module=re,
        os_module=os,
        httpx_module=httpx,
        urljoin_fn=urljoin,
        urlparse_fn=urlparse,
        image_ops=ImageOps,
        pil_available=PIL_AVAILABLE,
        static_dir=STATIC_DIR,
        logger=logger,
        models=models,
        func=func,
        retrieve_memories=retrieve_memories,
        resolve_memory_scope=resolve_memory_scope,
        format_long_term_memories=format_long_term_memories,
        build_layered_context_block=build_layered_context_block,
        ai_chat_memory_topk=AI_CHAT_MEMORY_TOPK,
        ai_chat_text_timeout_seconds=AI_CHAT_TEXT_TIMEOUT_SECONDS,
        ai_chat_temperature=AI_CHAT_TEMPERATURE,
        ai_chat_top_p=AI_CHAT_TOP_P,
        ai_chat_image_timeout_sec=AI_CHAT_IMAGE_TIMEOUT_SEC,
        ai_chat_image_caption_enabled=AI_CHAT_IMAGE_CAPTION_ENABLED,
        ai_chat_image_caption_model=AI_CHAT_IMAGE_CAPTION_MODEL,
        ai_chat_image_caption_max_output_tokens=AI_CHAT_IMAGE_CAPTION_MAX_OUTPUT_TOKENS,
        ai_chat_image_message_prefix=AI_CHAT_IMAGE_MESSAGE_PREFIX,
        provider_from_model=provider_from_model,
        assert_openrouter_model_allowed_for_pricing=assert_openrouter_model_allowed_for_pricing,
        call_ai_json=call_ai_json,
        ai_chat_history_item_cls=AIChatHistoryItem,
        ai_chat_image_item_cls=AIChatImageItem,
        secrets_module=secrets,
        get_novel_tag_names_impl=get_novel_tag_names_impl,
        get_episode_tag_names_impl=get_episode_tag_names_impl,
        format_ai_log_model_impl=_format_ai_log_model_impl,
        normalize_speech_gender_impl=normalize_speech_gender_impl,
        serialize_ai_response_impl=_serialize_ai_response_impl,
        extract_retry_max_from_request_json_impl=_extract_retry_max_from_request_json_impl,
        normalize_chunked_generation_payload_impl=_normalize_chunked_generation_payload_impl,
        build_chunked_novel_prompt_impl=_build_chunked_novel_prompt_impl,
        build_chunked_job_response_impl=_build_chunked_job_response_impl,
        count_ai_jobs_today_impl=_count_ai_jobs_today_impl,
        count_ai_usage_today_impl=_count_ai_usage_today_impl,
        ai_novel_paid_remaining_impl=_ai_novel_paid_remaining_impl,
        ai_novel_daily_max_for_user_impl=_ai_novel_daily_max_for_user_impl,
        ai_novel_remaining_for_user_impl=_ai_novel_remaining_for_user_impl,
        reserve_ai_novel_generation_slot_impl=_reserve_ai_novel_generation_slot_impl,
        is_ai_job_expired_impl=_is_ai_job_expired_impl,
        kill_expired_ai_jobs_impl=_kill_expired_ai_jobs_impl,
        should_retry_ai_error_impl=_should_retry_ai_error_impl,
        is_empty_ai_response_error_impl=_is_empty_ai_response_error_impl,
        call_ai_with_retry_impl=_call_ai_with_retry_impl,
        call_ai_with_retry_prompt_impl=_call_ai_with_retry_prompt_impl,
        notify_ai_job_user_impl=_notify_ai_job_user_impl,
        run_ai_job_impl=_run_ai_job_impl,
        build_ai_chat_style_guide_impl=_build_ai_chat_style_guide_impl,
        build_ai_chat_content_safety_rules_impl=_build_ai_chat_content_safety_rules_impl,
        build_ai_chat_system_instructions_impl=_build_ai_chat_system_instructions_impl,
        normalize_chat_text_for_match_impl=_normalize_chat_text_for_match_impl,
        build_ai_chat_branching_instruction_impl=_build_ai_chat_branching_instruction_impl,
        build_ai_chat_variation_instruction_impl=_build_ai_chat_variation_instruction_impl,
        score_ai_chat_followup_latency_impl=_score_ai_chat_followup_latency_impl,
        clip01_impl=_clip01_impl,
        build_ai_chat_profile_key_impl=_build_ai_chat_profile_key_impl,
        calc_user_personalization_weight_impl=_calc_user_personalization_weight_impl,
        update_profile_learning_stats_impl=_update_profile_learning_stats_impl,
        normalized_keyword_score_impl=_normalized_keyword_score_impl,
        extract_personality_keywords_impl=_extract_personality_keywords_impl,
        estimate_ai_reply_scores_impl=_estimate_ai_reply_scores_impl,
        estimate_user_followup_signal_scores_impl=_estimate_user_followup_signal_scores_impl,
        record_ai_chat_followup_feedback_impl=_record_ai_chat_followup_feedback_impl,
        build_ai_chat_engagement_learning_instruction_impl=_build_ai_chat_engagement_learning_instruction_impl,
        build_ai_chat_recommendation_map_impl=_build_ai_chat_recommendation_map_impl,
        build_public_profile_recommendation_map_impl=_build_public_profile_recommendation_map_impl,
        build_relationship_tone_rules_impl=_build_relationship_tone_rules_impl,
        build_multi_character_relationship_rules_impl=_build_multi_character_relationship_rules_impl,
        normalize_language_style_impl=_normalize_language_style_impl,
        build_language_style_rules_impl=_build_language_style_rules_impl,
        looks_like_fictional_character_name_impl=_looks_like_fictional_character_name_impl,
        long_reply_min_chars_impl=_long_reply_min_chars_impl,
        normalize_ai_chat_model_alias_impl=_normalize_ai_chat_model_alias_impl,
        resolve_ai_chat_provider_impl=_resolve_ai_chat_provider_impl,
        ai_chat_provider_candidates_impl=_ai_chat_provider_candidates_impl,
        default_ai_chat_openrouter_model_impl=_default_ai_chat_openrouter_model_impl,
        default_ai_chat_deepseek_model_impl=_default_ai_chat_deepseek_model_impl,
        resolve_ai_chat_candidate_model_impl=_resolve_ai_chat_candidate_model_impl,
        call_ai_chat_json_with_fallback_impl=_call_ai_chat_json_with_fallback_impl,
        regenerate_long_reply_if_needed_impl=_regenerate_long_reply_if_needed_impl,
        regenerate_auto_dialogue_if_needed_impl=_regenerate_auto_dialogue_if_needed_impl,
        build_ai_chat_history_text_impl=_build_ai_chat_history_text_impl,
        build_ai_chat_history_lines_impl=_build_ai_chat_history_lines_impl,
        collect_ai_chat_backfill_turns_impl=_collect_ai_chat_backfill_turns_impl,
        build_ai_chat_prompt_impl=_build_ai_chat_prompt_impl,
        build_auto_dialogue_prompt_impl=_build_auto_dialogue_prompt_impl,
        build_ai_chat_next_line_suggest_prompt_impl=_build_ai_chat_next_line_suggest_prompt_impl,
        fallback_next_line_suggestions_impl=_fallback_next_line_suggestions_impl,
        normalize_next_line_suggestion_impl=_normalize_next_line_suggestion_impl,
        normalize_ai_chat_image_url_impl=_normalize_ai_chat_image_url_impl,
        extract_error_detail_from_response_impl=_extract_error_detail_from_response_impl,
        extract_session_token_from_payload_impl=_extract_session_token_from_payload_impl,
        serialize_ai_chat_image_message_impl=_serialize_ai_chat_image_message_impl,
        parse_ai_chat_image_message_impl=_parse_ai_chat_image_message_impl,
        local_static_path_from_url_impl=_local_static_path_from_url_impl,
        build_data_url_from_local_image_impl=_build_data_url_from_local_image_impl,
        extract_image_field_from_payload_impl=_extract_image_field_from_payload_impl,
        read_secret_from_env_or_file_impl=_read_secret_from_env_or_file_impl,
        extract_openai_responses_output_text_impl=_extract_openai_responses_output_text_impl,
        describe_uploaded_chat_images_impl=_describe_uploaded_chat_images_impl,
        resolve_image_to_data_url_impl=_resolve_image_to_data_url_impl,
        extract_background_place_prompt_impl=_extract_background_place_prompt_impl,
        extract_ai_chat_images_from_generate_data_impl=_extract_ai_chat_images_from_generate_data_impl,
        score_ai_chat_image_quality_impl=_score_ai_chat_image_quality_impl,
    )
)
